-- ═══════════════════════════════════════════════════════════
-- GooALS — limpiar los títulos de gastronomía
--
-- El PDF de gastronomía repetía dos coletillas en 366 de sus 598 retos:
-- "en su contexto local" y "donde forma parte de la tradición local". No
-- dicen nada —la ciudad y el país ya van en su columna— y convertían
-- "Probar pad thai" en una frase de folleto.
--
--   Probar Pad thai en su contexto local            →  Probar pad thai
--   Probar Macarons donde forma parte de la...       →  Probar macarons
--   Probar Philly cheesesteak en su contexto local   →  Probar philly cheesesteak
--
-- Además el plato baja a minúscula, que es como se escribe en español, salvo
-- si lleva un nombre propio dentro ("Probar Tarta de Santiago" se queda).
--
-- Van también tres títulos que quedaron cojos cuando el generador aprendió a
-- quitar el "con guía": "Recorrer Addis Mercato gastronomico" y compañía.
--
-- ── Por qué UPDATE y no borrar e insertar ──────────────────
--
-- Un UPDATE conserva el id de la fila, y con él las coordenadas ya
-- geocodificadas y cualquier lista de usuario que lo tenga marcado. Borrar e
-- insertar perdería las dos cosas.
--
-- Se puede lanzar dos veces: la segunda no encuentra nada que cambiar.
-- ═══════════════════════════════════════════════════════════

update gooals_v2 g
set titulo = v.nuevo
from (values
  ('gastronomia', 'Probar Paella valenciana en su contexto local', 'Probar paella valenciana'),
  ('gastronomia', 'Probar Tortilla de patatas en su contexto local', 'Probar tortilla de patatas'),
  ('gastronomia', 'Probar Pulpo a feira en su contexto local', 'Probar pulpo a feira'),
  ('gastronomia', 'Probar Pintxos en su contexto local', 'Probar pintxos'),
  ('gastronomia', 'Probar Cochinillo asado en su contexto local', 'Probar cochinillo asado'),
  ('gastronomia', 'Probar Fabada asturiana en su contexto local', 'Probar fabada asturiana'),
  ('gastronomia', 'Probar Gazpacho andaluz en su contexto local', 'Probar gazpacho andaluz'),
  ('gastronomia', 'Probar Calçots con romesco en su contexto local', 'Probar calçots con romesco'),
  ('gastronomia', 'Probar Escudella i carn d''olla en su contexto local', 'Probar escudella i carn d''olla'),
  ('gastronomia', 'Probar Arroz negro en su contexto local', 'Probar arroz negro'),
  ('gastronomia', 'Probar Bacalao al pil-pil en su contexto local', 'Probar bacalao al pil-pil'),
  ('gastronomia', 'Probar Jamón iberico de bellota en su contexto local', 'Probar jamón ibérico de bellota'),
  ('gastronomia', 'Probar Francesinha en su contexto local', 'Probar francesinha'),
  ('gastronomia', 'Probar Bacalhau a Bras en su contexto local', 'Probar Bacalhau a Bras'),
  ('gastronomia', 'Probar Cataplana en su contexto local', 'Probar cataplana'),
  ('gastronomia', 'Probar Cozido das Furnas en su contexto local', 'Probar Cozido das Furnas'),
  ('gastronomia', 'Probar Pastel de nata recien horneado en su contexto local', 'Probar pastel de nata recien horneado'),
  ('gastronomia', 'Probar Pizza napolitana en su contexto local', 'Probar pizza napolitana'),
  ('gastronomia', 'Probar Pasta carbonara romana en su contexto local', 'Probar pasta carbonara romana'),
  ('gastronomia', 'Probar Cacio e pepe en su contexto local', 'Probar cacio e pepe'),
  ('gastronomia', 'Probar Amatriciana en su contexto local', 'Probar amatriciana'),
  ('gastronomia', 'Probar Tagliatelle al ragu en su contexto local', 'Probar tagliatelle al ragu'),
  ('gastronomia', 'Probar Tortellini in brodo en su contexto local', 'Probar tortellini in brodo'),
  ('gastronomia', 'Probar Risotto alla milanese en su contexto local', 'Probar risotto alla milanese'),
  ('gastronomia', 'Probar Ossobuco en su contexto local', 'Probar ossobuco'),
  ('gastronomia', 'Probar Pesto genovese en su contexto local', 'Probar pesto genovese'),
  ('gastronomia', 'Probar Focaccia genovese en su contexto local', 'Probar focaccia genovese'),
  ('gastronomia', 'Probar Arancini en su contexto local', 'Probar arancini'),
  ('gastronomia', 'Probar Pasta alla Norma en su contexto local', 'Probar Pasta alla Norma'),
  ('gastronomia', 'Probar Caponata siciliana en su contexto local', 'Probar caponata siciliana'),
  ('gastronomia', 'Probar Bistecca alla fiorentina en su contexto local', 'Probar bistecca alla fiorentina'),
  ('gastronomia', 'Probar Ribollita en su contexto local', 'Probar ribollita'),
  ('gastronomia', 'Probar Polenta con setas o ragú en su contexto local', 'Probar polenta con setas o ragú'),
  ('gastronomia', 'Probar Fondue de queso en su contexto local', 'Probar fondue de queso'),
  ('gastronomia', 'Probar Raclette en su contexto local', 'Probar raclette'),
  ('gastronomia', 'Probar Rosti en su contexto local', 'Probar rosti'),
  ('gastronomia', 'Probar Schnitzel vienes en su contexto local', 'Probar schnitzel vienes'),
  ('gastronomia', 'Probar Tafelspitz en su contexto local', 'Probar tafelspitz'),
  ('gastronomia', 'Probar Goulash en su contexto local', 'Probar goulash'),
  ('gastronomia', 'Probar Lángos en su contexto local', 'Probar lángos'),
  ('gastronomia', 'Probar Pierogi en su contexto local', 'Probar pierogi'),
  ('gastronomia', 'Probar Bigos en su contexto local', 'Probar bigos'),
  ('gastronomia', 'Probar Svícková en su contexto local', 'Probar svícková'),
  ('gastronomia', 'Probar Sauerbraten en su contexto local', 'Probar sauerbraten'),
  ('gastronomia', 'Probar Currywurst en su contexto local', 'Probar currywurst'),
  ('gastronomia', 'Probar Bratwurst de Nuremberg en su contexto local', 'Probar Bratwurst de Nuremberg'),
  ('gastronomia', 'Probar Fish and chips en su contexto local', 'Probar fish and chips'),
  ('gastronomia', 'Probar Sunday roast en su contexto local', 'Probar sunday roast'),
  ('gastronomia', 'Probar Full English breakfast en su contexto local', 'Probar Full English breakfast'),
  ('gastronomia', 'Probar Haggis en su contexto local', 'Probar haggis'),
  ('gastronomia', 'Probar Irish stew en su contexto local', 'Probar irish stew'),
  ('gastronomia', 'Probar Moules-frites en su contexto local', 'Probar moules-frites'),
  ('gastronomia', 'Probar Carbonnade flamande en su contexto local', 'Probar carbonnade flamande'),
  ('gastronomia', 'Probar Croque monsieur en su contexto local', 'Probar croque monsieur'),
  ('gastronomia', 'Probar Boeuf bourguignon en su contexto local', 'Probar boeuf bourguignon'),
  ('gastronomia', 'Probar Cassoulet en su contexto local', 'Probar cassoulet'),
  ('gastronomia', 'Probar Bouillabaisse en su contexto local', 'Probar bouillabaisse'),
  ('gastronomia', 'Probar Confit de canard en su contexto local', 'Probar confit de canard'),
  ('gastronomia', 'Probar Galette bretona en su contexto local', 'Probar galette bretona'),
  ('gastronomia', 'Probar Quiche lorraine en su contexto local', 'Probar quiche lorraine'),
  ('gastronomia', 'Probar Moussaka en su contexto local', 'Probar moussaka'),
  ('gastronomia', 'Probar Souvlaki en su contexto local', 'Probar souvlaki'),
  ('gastronomia', 'Probar Gyros en su contexto local', 'Probar gyros'),
  ('gastronomia', 'Probar Spanakopita en su contexto local', 'Probar spanakopita'),
  ('gastronomia', 'Probar Kleftiko en su contexto local', 'Probar kleftiko'),
  ('gastronomia', 'Probar Cevapi en su contexto local', 'Probar cevapi'),
  ('gastronomia', 'Probar Burek en su contexto local', 'Probar burek'),
  ('gastronomia', 'Probar Peka en su contexto local', 'Probar peka'),
  ('gastronomia', 'Probar Black risotto en su contexto local', 'Probar black risotto'),
  ('gastronomia', 'Probar Sarma en su contexto local', 'Probar sarma'),
  ('gastronomia', 'Probar Khachapuri en su contexto local', 'Probar khachapuri'),
  ('gastronomia', 'Probar Khinkali en su contexto local', 'Probar khinkali'),
  ('gastronomia', 'Probar Dolma en su contexto local', 'Probar dolma'),
  ('gastronomia', 'Probar Plov en su contexto local', 'Probar plov'),
  ('gastronomia', 'Probar Lagman en su contexto local', 'Probar lagman'),
  ('gastronomia', 'Probar Beshbarmak en su contexto local', 'Probar beshbarmak'),
  ('gastronomia', 'Probar Manti en su contexto local', 'Probar manti'),
  ('gastronomia', 'Probar Doner kebab en su contexto local', 'Probar doner kebab'),
  ('gastronomia', 'Probar Iskender kebab en su contexto local', 'Probar iskender kebab'),
  ('gastronomia', 'Probar Testi kebab en su contexto local', 'Probar testi kebab'),
  ('gastronomia', 'Probar Menemen en su contexto local', 'Probar menemen'),
  ('gastronomia', 'Probar Lahmacun en su contexto local', 'Probar lahmacun'),
  ('gastronomia', 'Probar Pide en su contexto local', 'Probar pide'),
  ('gastronomia', 'Probar Meze tradicional en su contexto local', 'Probar meze tradicional'),
  ('gastronomia', 'Probar Shakshuka en su contexto local', 'Probar shakshuka'),
  ('gastronomia', 'Probar Hummus en su contexto local', 'Probar hummus'),
  ('gastronomia', 'Probar Falafel en su contexto local', 'Probar falafel'),
  ('gastronomia', 'Probar Fattoush en su contexto local', 'Probar fattoush'),
  ('gastronomia', 'Probar Manakish en su contexto local', 'Probar manakish'),
  ('gastronomia', 'Probar Kibbeh en su contexto local', 'Probar kibbeh'),
  ('gastronomia', 'Probar Mansaf en su contexto local', 'Probar mansaf'),
  ('gastronomia', 'Probar Maqluba en su contexto local', 'Probar maqluba'),
  ('gastronomia', 'Probar Kabsa en su contexto local', 'Probar kabsa'),
  ('gastronomia', 'Probar Machboos en su contexto local', 'Probar machboos'),
  ('gastronomia', 'Probar Koshari en su contexto local', 'Probar koshari'),
  ('gastronomia', 'Probar Ful medames en su contexto local', 'Probar ful medames'),
  ('gastronomia', 'Probar Molokhia en su contexto local', 'Probar molokhia'),
  ('gastronomia', 'Probar Tagine en su contexto local', 'Probar tagine'),
  ('gastronomia', 'Probar Cuscus tradicional en su contexto local', 'Probar cuscus tradicional'),
  ('gastronomia', 'Probar Pastilla marroqui en su contexto local', 'Probar pastilla marroquí'),
  ('gastronomia', 'Probar Harira en su contexto local', 'Probar harira'),
  ('gastronomia', 'Probar Mechoui en su contexto local', 'Probar mechoui'),
  ('gastronomia', 'Probar Shakshouka tunecina en su contexto local', 'Probar shakshouka tunecina'),
  ('gastronomia', 'Probar Brik en su contexto local', 'Probar brik'),
  ('gastronomia', 'Probar Doro wat con injera en su contexto local', 'Probar doro wat con injera'),
  ('gastronomia', 'Probar Kitfo en su contexto local', 'Probar kitfo'),
  ('gastronomia', 'Probar Tibs en su contexto local', 'Probar tibs'),
  ('gastronomia', 'Probar Bunny chow en su contexto local', 'Probar bunny chow'),
  ('gastronomia', 'Probar Bobotie en su contexto local', 'Probar bobotie'),
  ('gastronomia', 'Probar Braai en su contexto local', 'Probar braai'),
  ('gastronomia', 'Probar Nyama choma en su contexto local', 'Probar nyama choma'),
  ('gastronomia', 'Probar Ugali con guiso en su contexto local', 'Probar ugali con guiso'),
  ('gastronomia', 'Probar Jollof rice en su contexto local', 'Probar jollof rice'),
  ('gastronomia', 'Probar Suya en su contexto local', 'Probar suya'),
  ('gastronomia', 'Probar Egusi soup en su contexto local', 'Probar egusi soup'),
  ('gastronomia', 'Probar Fufu con sopa local en su contexto local', 'Probar fufu con sopa local'),
  ('gastronomia', 'Probar Thieboudienne en su contexto local', 'Probar thieboudienne'),
  ('gastronomia', 'Probar Yassa poulet en su contexto local', 'Probar yassa poulet'),
  ('gastronomia', 'Probar Moqueca en su contexto local', 'Probar moqueca'),
  ('gastronomia', 'Probar Feijoada en su contexto local', 'Probar feijoada'),
  ('gastronomia', 'Probar Pao de queijo en su contexto local', 'Probar pao de queijo'),
  ('gastronomia', 'Probar Churrasco en su contexto local', 'Probar churrasco'),
  ('gastronomia', 'Probar Acaraje en su contexto local', 'Probar acaraje'),
  ('gastronomia', 'Probar Empanadas salteñas en su contexto local', 'Probar empanadas salteñas'),
  ('gastronomia', 'Probar Asado argentino en su contexto local', 'Probar asado argentino'),
  ('gastronomia', 'Probar Milanesa napolitana en su contexto local', 'Probar milanesa napolitana'),
  ('gastronomia', 'Probar Locro en su contexto local', 'Probar locro'),
  ('gastronomia', 'Probar Chivito en su contexto local', 'Probar chivito'),
  ('gastronomia', 'Probar Cazuela chilena en su contexto local', 'Probar cazuela chilena'),
  ('gastronomia', 'Probar Pastel de choclo en su contexto local', 'Probar pastel de choclo'),
  ('gastronomia', 'Probar Completo chileno en su contexto local', 'Probar completo chileno'),
  ('gastronomia', 'Probar Ceviche peruano en su contexto local', 'Probar ceviche peruano'),
  ('gastronomia', 'Probar Lomo saltado en su contexto local', 'Probar lomo saltado'),
  ('gastronomia', 'Probar Aji de gallina en su contexto local', 'Probar aji de gallina'),
  ('gastronomia', 'Probar Causa limeña en su contexto local', 'Probar causa limeña'),
  ('gastronomia', 'Probar Anticuchos en su contexto local', 'Probar anticuchos'),
  ('gastronomia', 'Probar Pachamanca en su contexto local', 'Probar pachamanca'),
  ('gastronomia', 'Probar Salteñas en su contexto local', 'Probar salteñas'),
  ('gastronomia', 'Probar Silpancho en su contexto local', 'Probar silpancho'),
  ('gastronomia', 'Probar Llapingachos en su contexto local', 'Probar llapingachos'),
  ('gastronomia', 'Probar Encebollado en su contexto local', 'Probar encebollado'),
  ('gastronomia', 'Probar Arepas en su contexto local', 'Probar arepas'),
  ('gastronomia', 'Probar Bandeja paisa en su contexto local', 'Probar bandeja paisa'),
  ('gastronomia', 'Probar Ajiaco santafereño en su contexto local', 'Probar ajiaco santafereño'),
  ('gastronomia', 'Probar Lechona en su contexto local', 'Probar lechona'),
  ('gastronomia', 'Probar Sancocho en su contexto local', 'Probar sancocho'),
  ('gastronomia', 'Probar Ropa vieja en su contexto local', 'Probar ropa vieja'),
  ('gastronomia', 'Probar Lechon asado cubano en su contexto local', 'Probar lechon asado cubano'),
  ('gastronomia', 'Probar Mofongo en su contexto local', 'Probar mofongo'),
  ('gastronomia', 'Probar Jerk chicken en su contexto local', 'Probar jerk chicken'),
  ('gastronomia', 'Probar Ackee and saltfish en su contexto local', 'Probar ackee and saltfish'),
  ('gastronomia', 'Probar Pepperpot en su contexto local', 'Probar pepperpot'),
  ('gastronomia', 'Probar Tacos al pastor en su contexto local', 'Probar tacos al pastor'),
  ('gastronomia', 'Probar Tacos de birria en su contexto local', 'Probar tacos de birria'),
  ('gastronomia', 'Probar Cochinita pibil en su contexto local', 'Probar cochinita pibil'),
  ('gastronomia', 'Probar Mole poblano en su contexto local', 'Probar mole poblano'),
  ('gastronomia', 'Probar Pozole en su contexto local', 'Probar pozole'),
  ('gastronomia', 'Probar Tamales en su contexto local', 'Probar tamales'),
  ('gastronomia', 'Probar Chiles en nogada en su contexto local', 'Probar chiles en nogada'),
  ('gastronomia', 'Probar Tlayudas en su contexto local', 'Probar tlayudas'),
  ('gastronomia', 'Probar Ceviche mexicano en su contexto local', 'Probar ceviche mexicano'),
  ('gastronomia', 'Probar Pupusas en su contexto local', 'Probar pupusas'),
  ('gastronomia', 'Probar Pepian en su contexto local', 'Probar pepian'),
  ('gastronomia', 'Probar Gallo pinto en su contexto local', 'Probar gallo pinto'),
  ('gastronomia', 'Probar Casado en su contexto local', 'Probar casado'),
  ('gastronomia', 'Probar Rondon en su contexto local', 'Probar rondon'),
  ('gastronomia', 'Probar Poutine en su contexto local', 'Probar poutine'),
  ('gastronomia', 'Probar Smoked meat sandwich en su contexto local', 'Probar smoked meat sandwich'),
  ('gastronomia', 'Probar Lobster roll en su contexto local', 'Probar lobster roll'),
  ('gastronomia', 'Probar Clam chowder en su contexto local', 'Probar clam chowder'),
  ('gastronomia', 'Probar New York pizza slice en su contexto local', 'Probar New York pizza slice'),
  ('gastronomia', 'Probar Bagel con cream cheese y salmón en su contexto local', 'Probar bagel con cream cheese y salmón'),
  ('gastronomia', 'Probar Pastrami sandwich en su contexto local', 'Probar pastrami sandwich'),
  ('gastronomia', 'Probar Philly cheesesteak en su contexto local', 'Probar philly cheesesteak'),
  ('gastronomia', 'Probar Chicago deep-dish pizza en su contexto local', 'Probar chicago deep-dish pizza'),
  ('gastronomia', 'Probar Texas barbecue brisket en su contexto local', 'Probar texas barbecue brisket'),
  ('gastronomia', 'Probar Kansas City barbecue en su contexto local', 'Probar Kansas City barbecue'),
  ('gastronomia', 'Probar Nashville hot chicken en su contexto local', 'Probar nashville hot chicken'),
  ('gastronomia', 'Probar Louisiana gumbo en su contexto local', 'Probar louisiana gumbo'),
  ('gastronomia', 'Probar Jambalaya en su contexto local', 'Probar jambalaya'),
  ('gastronomia', 'Probar Crawfish boil en su contexto local', 'Probar crawfish boil'),
  ('gastronomia', 'Probar Biscuits and gravy en su contexto local', 'Probar biscuits and gravy'),
  ('gastronomia', 'Probar Hawaiian poke en su contexto local', 'Probar hawaiian poke'),
  ('gastronomia', 'Probar Sushi omakase en su contexto local', 'Probar sushi omakase'),
  ('gastronomia', 'Probar Ramen tonkotsu en su contexto local', 'Probar ramen tonkotsu'),
  ('gastronomia', 'Probar Ramen shoyu en su contexto local', 'Probar ramen shoyu'),
  ('gastronomia', 'Probar Okonomiyaki en su contexto local', 'Probar okonomiyaki'),
  ('gastronomia', 'Probar Takoyaki en su contexto local', 'Probar takoyaki'),
  ('gastronomia', 'Probar Kaiseki en su contexto local', 'Probar kaiseki'),
  ('gastronomia', 'Probar Tempura en su contexto local', 'Probar tempura'),
  ('gastronomia', 'Probar Yakitori en su contexto local', 'Probar yakitori'),
  ('gastronomia', 'Probar Tonkatsu en su contexto local', 'Probar tonkatsu'),
  ('gastronomia', 'Probar Unagi kabayaki en su contexto local', 'Probar unagi kabayaki'),
  ('gastronomia', 'Probar Soba artesanal en su contexto local', 'Probar soba artesanal'),
  ('gastronomia', 'Probar Udon en su contexto local', 'Probar udon'),
  ('gastronomia', 'Probar Japanese curry en su contexto local', 'Probar japanese curry'),
  ('gastronomia', 'Probar Korean barbecue en su contexto local', 'Probar korean barbecue'),
  ('gastronomia', 'Probar Bibimbap en su contexto local', 'Probar bibimbap'),
  ('gastronomia', 'Probar Kimchi jjigae en su contexto local', 'Probar kimchi jjigae'),
  ('gastronomia', 'Probar Tteokbokki en su contexto local', 'Probar tteokbokki'),
  ('gastronomia', 'Probar Samgyetang en su contexto local', 'Probar samgyetang'),
  ('gastronomia', 'Probar Jajangmyeon en su contexto local', 'Probar jajangmyeon'),
  ('gastronomia', 'Probar Peking duck en su contexto local', 'Probar peking duck'),
  ('gastronomia', 'Probar Xiaolongbao en su contexto local', 'Probar xiaolongbao'),
  ('gastronomia', 'Probar Dim sum en su contexto local', 'Probar dim sum'),
  ('gastronomia', 'Probar Hot pot de Sichuan en su contexto local', 'Probar Hot pot de Sichuan'),
  ('gastronomia', 'Probar Mapo tofu en su contexto local', 'Probar mapo tofu'),
  ('gastronomia', 'Probar Biang biang noodles en su contexto local', 'Probar biang biang noodles'),
  ('gastronomia', 'Probar Lanzhou beef noodles en su contexto local', 'Probar lanzhou beef noodles'),
  ('gastronomia', 'Probar Char siu en su contexto local', 'Probar char siu'),
  ('gastronomia', 'Probar Hainanese chicken rice en su contexto local', 'Probar hainanese chicken rice'),
  ('gastronomia', 'Probar Chilli crab en su contexto local', 'Probar chilli crab'),
  ('gastronomia', 'Probar Laksa en su contexto local', 'Probar laksa'),
  ('gastronomia', 'Probar Nasi lemak en su contexto local', 'Probar nasi lemak'),
  ('gastronomia', 'Probar Char kway teow en su contexto local', 'Probar char kway teow'),
  ('gastronomia', 'Probar Roti canai en su contexto local', 'Probar roti canai'),
  ('gastronomia', 'Probar Beef rendang en su contexto local', 'Probar beef rendang'),
  ('gastronomia', 'Probar Nasi goreng en su contexto local', 'Probar nasi goreng'),
  ('gastronomia', 'Probar Satay en su contexto local', 'Probar satay'),
  ('gastronomia', 'Probar Babi guling en su contexto local', 'Probar babi guling'),
  ('gastronomia', 'Probar Gado-gado en su contexto local', 'Probar gado-gado'),
  ('gastronomia', 'Probar Pho en su contexto local', 'Probar pho'),
  ('gastronomia', 'Probar Bun cha en su contexto local', 'Probar bun cha'),
  ('gastronomia', 'Probar Banh mi en su contexto local', 'Probar banh mi'),
  ('gastronomia', 'Probar Cao lau en su contexto local', 'Probar cao lau'),
  ('gastronomia', 'Probar Bun bo Hue en su contexto local', 'Probar Bun bo Hue'),
  ('gastronomia', 'Probar Pad thai en su contexto local', 'Probar pad thai'),
  ('gastronomia', 'Probar Tom yum goong en su contexto local', 'Probar tom yum goong'),
  ('gastronomia', 'Probar Green curry en su contexto local', 'Probar green curry'),
  ('gastronomia', 'Probar Khao soi en su contexto local', 'Probar khao soi'),
  ('gastronomia', 'Probar Som tam en su contexto local', 'Probar som tam'),
  ('gastronomia', 'Probar Massaman curry en su contexto local', 'Probar massaman curry'),
  ('gastronomia', 'Probar Boat noodles en su contexto local', 'Probar boat noodles'),
  ('gastronomia', 'Probar Adobo filipino en su contexto local', 'Probar adobo filipino'),
  ('gastronomia', 'Probar Sinigang en su contexto local', 'Probar sinigang'),
  ('gastronomia', 'Probar Lechon en su contexto local', 'Probar lechon'),
  ('gastronomia', 'Probar Sisig en su contexto local', 'Probar sisig'),
  ('gastronomia', 'Probar Chicken inasal en su contexto local', 'Probar chicken inasal'),
  ('gastronomia', 'Probar Biryani de Hyderabad en su contexto local', 'Probar Biryani de Hyderabad'),
  ('gastronomia', 'Probar Butter chicken en su contexto local', 'Probar butter chicken'),
  ('gastronomia', 'Probar Masala dosa en su contexto local', 'Probar masala dosa'),
  ('gastronomia', 'Probar Thali regional en su contexto local', 'Probar thali regional'),
  ('gastronomia', 'Probar Chole bhature en su contexto local', 'Probar chole bhature'),
  ('gastronomia', 'Probar Rogan josh en su contexto local', 'Probar rogan josh'),
  ('gastronomia', 'Probar Vindaloo en su contexto local', 'Probar vindaloo'),
  ('gastronomia', 'Probar Vada pav en su contexto local', 'Probar vada pav'),
  ('gastronomia', 'Probar Pav bhaji en su contexto local', 'Probar pav bhaji'),
  ('gastronomia', 'Probar Pani puri en su contexto local', 'Probar pani puri'),
  ('gastronomia', 'Probar Kottu roti en su contexto local', 'Probar kottu roti'),
  ('gastronomia', 'Probar Rice and curry en su contexto local', 'Probar rice and curry'),
  ('gastronomia', 'Probar Hoppers en su contexto local', 'Probar hoppers'),
  ('gastronomia', 'Probar Dal bhat en su contexto local', 'Probar dal bhat'),
  ('gastronomia', 'Probar Momos en su contexto local', 'Probar momos'),
  ('gastronomia', 'Probar Thukpa en su contexto local', 'Probar thukpa'),
  ('gastronomia', 'Probar Mongolian hot pot en su contexto local', 'Probar mongolian hot pot'),
  ('gastronomia', 'Probar Buuz en su contexto local', 'Probar buuz'),
  ('gastronomia', 'Probar Meat pie australiano en su contexto local', 'Probar meat pie australiano'),
  ('gastronomia', 'Probar Barramundi en su contexto local', 'Probar barramundi'),
  ('gastronomia', 'Probar Hangi maori en su contexto local', 'Probar hangi maori'),
  ('gastronomia', 'Probar Green-lipped mussels en su contexto local', 'Probar green-lipped mussels'),
  ('gastronomia', 'Probar Lovo feast en su contexto local', 'Probar lovo feast'),
  ('gastronomia', 'Visitar un mercado de especias marroqui', 'Visitar un mercado de especias marroquí'),
  ('gastronomia', 'Probar Croissant de mantequilla artesanal donde forma parte de la tradicion local', 'Probar croissant de mantequilla artesanal'),
  ('gastronomia', 'Probar Pain au chocolat donde forma parte de la tradicion local', 'Probar pain au chocolat'),
  ('gastronomia', 'Probar Macarons donde forma parte de la tradicion local', 'Probar macarons'),
  ('gastronomia', 'Probar Canelé donde forma parte de la tradicion local', 'Probar canelé'),
  ('gastronomia', 'Probar Kouign-amann donde forma parte de la tradicion local', 'Probar kouign-amann'),
  ('gastronomia', 'Probar Tarte Tatin donde forma parte de la tradicion local', 'Probar Tarte Tatin'),
  ('gastronomia', 'Probar Crepe con mantequilla y azucar donde forma parte de la tradicion local', 'Probar crepe con mantequilla y azucar'),
  ('gastronomia', 'Probar Madeleine donde forma parte de la tradicion local', 'Probar madeleine'),
  ('gastronomia', 'Probar Pastel de nata donde forma parte de la tradicion local', 'Probar pastel de nata'),
  ('gastronomia', 'Probar Travesseiros de Sintra donde forma parte de la tradicion local', 'Probar Travesseiros de Sintra'),
  ('gastronomia', 'Probar Ensaimada donde forma parte de la tradicion local', 'Probar ensaimada'),
  ('gastronomia', 'Probar Tarta de Santiago donde forma parte de la tradicion local', 'Probar Tarta de Santiago'),
  ('gastronomia', 'Probar Crema catalana donde forma parte de la tradicion local', 'Probar crema catalana'),
  ('gastronomia', 'Probar Churros con chocolate donde forma parte de la tradicion local', 'Probar churros con chocolate'),
  ('gastronomia', 'Probar Torrija tradicional donde forma parte de la tradicion local', 'Probar torrija tradicional'),
  ('gastronomia', 'Probar Cannoli donde forma parte de la tradicion local', 'Probar cannoli'),
  ('gastronomia', 'Probar Sfogliatella donde forma parte de la tradicion local', 'Probar sfogliatella'),
  ('gastronomia', 'Probar Tiramisu donde forma parte de la tradicion local', 'Probar tiramisu'),
  ('gastronomia', 'Probar Gelato artesanal donde forma parte de la tradicion local', 'Probar gelato artesanal'),
  ('gastronomia', 'Probar Panettone artesanal donde forma parte de la tradicion local', 'Probar panettone artesanal'),
  ('gastronomia', 'Probar Pandoro donde forma parte de la tradicion local', 'Probar pandoro'),
  ('gastronomia', 'Probar Sachertorte donde forma parte de la tradicion local', 'Probar sachertorte'),
  ('gastronomia', 'Probar Apfelstrudel donde forma parte de la tradicion local', 'Probar apfelstrudel'),
  ('gastronomia', 'Probar Kaiserschmarrn donde forma parte de la tradicion local', 'Probar kaiserschmarrn'),
  ('gastronomia', 'Probar Black Forest cake donde forma parte de la tradicion local', 'Probar Black Forest cake'),
  ('gastronomia', 'Probar Berliner donde forma parte de la tradicion local', 'Probar berliner'),
  ('gastronomia', 'Probar Stroopwafel donde forma parte de la tradicion local', 'Probar stroopwafel'),
  ('gastronomia', 'Probar Poffertjes donde forma parte de la tradicion local', 'Probar poffertjes'),
  ('gastronomia', 'Probar Belgian waffle donde forma parte de la tradicion local', 'Probar belgian waffle'),
  ('gastronomia', 'Probar Speculoos donde forma parte de la tradicion local', 'Probar speculoos'),
  ('gastronomia', 'Probar Pastel de tres leches donde forma parte de la tradicion local', 'Probar pastel de tres leches'),
  ('gastronomia', 'Probar Alfajor donde forma parte de la tradicion local', 'Probar alfajor'),
  ('gastronomia', 'Probar Dulce de leche artesanal donde forma parte de la tradicion local', 'Probar dulce de leche artesanal'),
  ('gastronomia', 'Probar Churros rellenos donde forma parte de la tradicion local', 'Probar churros rellenos'),
  ('gastronomia', 'Probar Brigadeiro donde forma parte de la tradicion local', 'Probar brigadeiro'),
  ('gastronomia', 'Probar Quindim donde forma parte de la tradicion local', 'Probar quindim'),
  ('gastronomia', 'Probar Suspiro limeño donde forma parte de la tradicion local', 'Probar suspiro limeño'),
  ('gastronomia', 'Probar Picarones donde forma parte de la tradicion local', 'Probar picarones'),
  ('gastronomia', 'Probar Alfajores peruanos donde forma parte de la tradicion local', 'Probar alfajores peruanos'),
  ('gastronomia', 'Probar Buñuelos donde forma parte de la tradicion local', 'Probar buñuelos'),
  ('gastronomia', 'Probar Obleas con arequipe donde forma parte de la tradicion local', 'Probar obleas con arequipe'),
  ('gastronomia', 'Probar Quesillo donde forma parte de la tradicion local', 'Probar quesillo'),
  ('gastronomia', 'Probar Flan cubano donde forma parte de la tradicion local', 'Probar flan cubano'),
  ('gastronomia', 'Probar Tres leches nicaraguense donde forma parte de la tradicion local', 'Probar tres leches nicaraguense'),
  ('gastronomia', 'Probar Pan de muerto donde forma parte de la tradicion local', 'Probar pan de muerto'),
  ('gastronomia', 'Probar Concha mexicana donde forma parte de la tradicion local', 'Probar concha mexicana'),
  ('gastronomia', 'Probar Churros mexicanos donde forma parte de la tradicion local', 'Probar churros mexicanos'),
  ('gastronomia', 'Probar Pastel de elote donde forma parte de la tradicion local', 'Probar pastel de elote'),
  ('gastronomia', 'Probar Beignets donde forma parte de la tradicion local', 'Probar beignets'),
  ('gastronomia', 'Probar Key lime pie donde forma parte de la tradicion local', 'Probar key lime pie'),
  ('gastronomia', 'Probar New York cheesecake donde forma parte de la tradicion local', 'Probar New York cheesecake'),
  ('gastronomia', 'Probar Boston cream pie donde forma parte de la tradicion local', 'Probar boston cream pie'),
  ('gastronomia', 'Probar Pecan pie donde forma parte de la tradicion local', 'Probar pecan pie'),
  ('gastronomia', 'Probar Apple pie donde forma parte de la tradicion local', 'Probar apple pie'),
  ('gastronomia', 'Probar Donut artesanal donde forma parte de la tradicion local', 'Probar donut artesanal'),
  ('gastronomia', 'Probar Maple taffy sobre nieve donde forma parte de la tradicion local', 'Probar maple taffy sobre nieve'),
  ('gastronomia', 'Probar Butter tart donde forma parte de la tradicion local', 'Probar butter tart'),
  ('gastronomia', 'Probar Nanaimo bar donde forma parte de la tradicion local', 'Probar nanaimo bar'),
  ('gastronomia', 'Probar Mochi tradicional donde forma parte de la tradicion local', 'Probar mochi tradicional'),
  ('gastronomia', 'Probar Dorayaki donde forma parte de la tradicion local', 'Probar dorayaki'),
  ('gastronomia', 'Probar Taiyaki donde forma parte de la tradicion local', 'Probar taiyaki'),
  ('gastronomia', 'Probar Japanese cheesecake donde forma parte de la tradicion local', 'Probar japanese cheesecake'),
  ('gastronomia', 'Probar Matcha parfait donde forma parte de la tradicion local', 'Probar matcha parfait'),
  ('gastronomia', 'Probar Castella donde forma parte de la tradicion local', 'Probar castella'),
  ('gastronomia', 'Probar Bingsu donde forma parte de la tradicion local', 'Probar bingsu'),
  ('gastronomia', 'Probar Hotteok donde forma parte de la tradicion local', 'Probar hotteok'),
  ('gastronomia', 'Probar Mooncake donde forma parte de la tradicion local', 'Probar mooncake'),
  ('gastronomia', 'Probar Egg tart donde forma parte de la tradicion local', 'Probar egg tart'),
  ('gastronomia', 'Probar Tangyuan donde forma parte de la tradicion local', 'Probar tangyuan'),
  ('gastronomia', 'Probar Pineapple cake donde forma parte de la tradicion local', 'Probar pineapple cake'),
  ('gastronomia', 'Probar Bubble tea original donde forma parte de la tradicion local', 'Probar bubble tea original'),
  ('gastronomia', 'Probar Mango sticky rice donde forma parte de la tradicion local', 'Probar mango sticky rice'),
  ('gastronomia', 'Probar Khanom krok donde forma parte de la tradicion local', 'Probar khanom krok'),
  ('gastronomia', 'Probar Thai roti donde forma parte de la tradicion local', 'Probar thai roti'),
  ('gastronomia', 'Probar Cendol donde forma parte de la tradicion local', 'Probar cendol'),
  ('gastronomia', 'Probar Kaya toast donde forma parte de la tradicion local', 'Probar kaya toast'),
  ('gastronomia', 'Probar Pandan cake donde forma parte de la tradicion local', 'Probar pandan cake'),
  ('gastronomia', 'Probar Martabak manis donde forma parte de la tradicion local', 'Probar martabak manis'),
  ('gastronomia', 'Probar Klepon donde forma parte de la tradicion local', 'Probar klepon'),
  ('gastronomia', 'Probar Halo-halo donde forma parte de la tradicion local', 'Probar halo-halo'),
  ('gastronomia', 'Probar Bibingka donde forma parte de la tradicion local', 'Probar bibingka'),
  ('gastronomia', 'Probar Mango float donde forma parte de la tradicion local', 'Probar mango float'),
  ('gastronomia', 'Probar Kulfi donde forma parte de la tradicion local', 'Probar kulfi'),
  ('gastronomia', 'Probar Gulab jamun donde forma parte de la tradicion local', 'Probar gulab jamun'),
  ('gastronomia', 'Probar Jalebi donde forma parte de la tradicion local', 'Probar jalebi'),
  ('gastronomia', 'Probar Rasgulla donde forma parte de la tradicion local', 'Probar rasgulla'),
  ('gastronomia', 'Probar Mysore pak donde forma parte de la tradicion local', 'Probar mysore pak'),
  ('gastronomia', 'Probar Watalappam donde forma parte de la tradicion local', 'Probar watalappam'),
  ('gastronomia', 'Probar Baklava donde forma parte de la tradicion local', 'Probar baklava'),
  ('gastronomia', 'Probar Kunefe donde forma parte de la tradicion local', 'Probar kunefe'),
  ('gastronomia', 'Probar Turkish delight donde forma parte de la tradicion local', 'Probar turkish delight'),
  ('gastronomia', 'Probar Lokma donde forma parte de la tradicion local', 'Probar lokma'),
  ('gastronomia', 'Probar Basbousa donde forma parte de la tradicion local', 'Probar basbousa'),
  ('gastronomia', 'Probar Knafeh donde forma parte de la tradicion local', 'Probar knafeh'),
  ('gastronomia', 'Probar Maamoul donde forma parte de la tradicion local', 'Probar maamoul'),
  ('gastronomia', 'Probar Halva donde forma parte de la tradicion local', 'Probar halva'),
  ('gastronomia', 'Probar Chebakia donde forma parte de la tradicion local', 'Probar chebakia'),
  ('gastronomia', 'Probar Msemen con miel donde forma parte de la tradicion local', 'Probar msemen con miel'),
  ('gastronomia', 'Probar Koeksisters donde forma parte de la tradicion local', 'Probar koeksisters'),
  ('gastronomia', 'Probar Malva pudding donde forma parte de la tradicion local', 'Probar malva pudding'),
  ('gastronomia', 'Probar Melktert donde forma parte de la tradicion local', 'Probar melktert'),
  ('gastronomia', 'Probar Lamington donde forma parte de la tradicion local', 'Probar lamington'),
  ('gastronomia', 'Probar Pavlova donde forma parte de la tradicion local', 'Probar pavlova'),
  ('gastronomia', 'Probar Anzac biscuit donde forma parte de la tradicion local', 'Probar anzac biscuit'),
  ('gastronomia', 'Probar Hokey pokey ice cream donde forma parte de la tradicion local', 'Probar hokey pokey ice cream'),
  ('gastronomia', 'Participar en una cata de cafe de especialidad', 'Participar en una cata de café de especialidad'),
  ('gastronomia', 'Participar en ceremonia etiope del cafe', 'Participar en ceremonia etiope del café'),
  ('gastronomia', 'Visitar una finca de cafe de altura', 'Visitar una finca de café de altura'),
  ('gastronomia', 'Hacer un cupping profesional de cafe', 'Hacer un cupping profesional de café'),
  ('gastronomia', 'Aprender cocina marroqui en un riad', 'Aprender cocina marroquí en un riad'),
  ('gastronomia', 'Recorrer Addis Mercato gastronomico', 'Recorrer Addis Mercato'),
  ('gastronomia', 'Recorrer un mercado de Lagos local', 'Recorrer un mercado de Lagos'),
  ('cultura', 'Visitar las iglesias rupestres de Tigray seguro', 'Visitar las iglesias rupestres de Tigray')
) as v(categoria, viejo, nuevo)
where g.categoria = v.categoria and g.titulo = v.viejo;


-- ── Comprobación ───────────────────────────────────────────
-- Debe salir 0: ningún título con la coletilla del PDF.
select count(*) as con_relleno
from gooals_v2
where titulo like '%contexto local%' or titulo like '%tradicion local%';
