-- ═══════════════════════════════════════════════════════════
-- GooALS — sincronizar Supabase con el catálogo
--
-- Esto NO borra por lista de nombres viejos: borra todo lo que NO esté en el
-- catálogo actual. Da igual en qué estado esté la tabla — al terminar coincide
-- con el fichero, y volver a ejecutarlo no hace nada.
--
-- Solo toca las cinco categorías que han cambiado. viajes (2.000) y
-- gastronomía (598) están idénticas y no se mencionan siquiera.
--
-- Ningún DELETE puede llevarse un gooal que alguien tenga en su lista.
--
-- Supabase avisará de "destructive operations": sí, hay DELETE. Run without RLS.
-- ═══════════════════════════════════════════════════════════

-- ── deporte (605 títulos buenos) ──
delete from gooals_v2 g
where g.categoria = 'deporte'
  and g.titulo not in (
  'Hacer tu primera dominada pronada',
  'Hacer tu primera dominada supina',
  'Hacer una sentadilla profunda con talones apoyados',
  'Tocar el suelo con las palmas manteniendo las rodillas extendidas',
  'Completar una clase de yoga de 90 minutos',
  'Hacer tu primer L-sit de 5 segundos',
  'Hacer un handstand contra pared de 30 segundos',
  'Mantener una sentadilla profunda 2 minutos',
  'Hacer dominadas estrictas',
  'Hacer tu primera pistol squat libre',
  'Hacer una tuck back lever de 10 segundos',
  'Hacer una tuck front lever de 10 segundos',
  'Mantener un handstand libre segundos',
  'Mantener una postura de puente 30 segundos',
  'Caminar 10 m sobre las manos',
  'Conseguir un split frontal',
  'Conseguir un split lateral',
  'Hacer 10 pistol squats por pierna',
  'Hacer un backflip en gimnasio',
  'Hacer un muscle-up estricto en barra',
  'Mantener un L-sit 20 segundos',
  'Hacer un muscle-up estricto en anillas',
  'Mantener un back lever completo 5 segundos',
  'Mantener un front lever completo 5 segundos',
  'Mantener una bandera humana 5 segundos',
  'Subir el equivalente a plantas',
  'Completar una clase de spinning',
  'Completar 10 clases de spinning',
  'Completar de cardio en zona',
  'Completar una sesión de cardio indoor de 3 máquinas diferentes',
  'Hacer un test de 2.000 m en remo y repetirlo 8 semanas después',
  'Hacer un test de 20 minutos en BikeErg',
  'Completar 50 km en bicicleta de carretera en un día',
  'Completar 100 km en bicicleta de carretera en un día',
  'Completar 200 km en bicicleta de carretera en un día',
  'Acumular 1.000 m de desnivel en bicicleta',
  'Subir un puerto de montaña de sin bajarse de la bicicleta',
  'Subir dos puertos en una misma salida sin bajarse de la bicicleta',
  'Subir tres puertos en una misma salida sin bajarse de la bicicleta',
  'Subir un puerto de categoría especial sin bajarse de la bicicleta',
  'Hacer una ruta ciclista de 50 km',
  'Hacer una ruta ciclista de 50 km por un parque natural',
  'Hacer una ruta ciclista de 50 km por una isla',
  'Hacer una ruta ciclista de 50 km con alforjas',
  'Completar una ruta gravel de 100 km',
  'Hacer bikepacking de una noche',
  'Hacer una ruta e-bike de montaña de 50 km',
  'Hacer una salida en velódromo',
  'Participar en una marcha cicloturista',
  'Reparar un pinchazo tubeless en ruta',
  'Cruzar una frontera en bicicleta',
  'Hacer bikepacking de un fin de semana',
  'Hacer una contrarreloj de 20 km',
  'Mantener un track stand 30 segundos',
  'Completar un gran fondo',
  'Completar una ruta ciclista de 3 días',
  'Completar una ruta de 100 km sin parar más de 10 minutos',
  'Completar una ruta de enduro MTB',
  'Mantener 30 km/h de media durante 40 km',
  'Subir 1.000 m de desnivel en menos de una hora acumulada',
  'Completar una ruta MTB de 50 km',
  'Completar una ruta MTB de 100 km',
  'Pedalear 5 horas en un mismo día',
  'Caminar al menos 10.000 pasos durante 7 días consecutivos',
  'Hacer al menos de actividad física durante días consecutivos',
  'Entrenar con 10 personas diferentes',
  'Enseñar a un amigo una habilidad deportiva que domines',
  'Entrenar antes de las 7:00 durante 10 días',
  'Hacer 10 entrenamientos bajo lluvia moderada de forma segura',
  'Correr 3 días por semana durante 12 semanas',
  'Entrenar fuerza 3 días por semana durante 12 semanas',
  'Hacer 30 entrenamientos al amanecer',
  'Probar deportes distintos en meses',
  'Completar un reto deportivo nuevo cada mes durante un año',
  'Hacer 100 días de actividad al aire libre en un año',
  'Hacer una actividad deportiva en 10 países diferentes',
  'Hacer una actividad deportiva en 5 continentes',
  'Completar entrenamientos registrados',
  'Bailar durante 2 horas en una social dance',
  'Bailar salsa durante 30 minutos seguidos',
  'Completar 60 minutos de zumba sin parar',
  'Completar una barra de ballet completa',
  'Hacer 30 días de práctica de baile de 15 minutos',
  'Hacer una rutina de shuffle de 2 minutos',
  'Participar en una exhibición amateur de baile',
  'Marcar un punto en ultimate frisbee',
  'Mantener un peloteo de 20 golpes en teqball',
  'Participar en unos juegos Highland amateur adaptados',
  'Lanzar un caber de entrenamiento',
  'Completar una sesión de 30 minutos en parque de trampolines',
  'Hacer una sesión de trampolín deportivo',
  'Hacer parapente biplaza en montaña',
  'Hacer parapente biplaza sobre costa',
  'Hacer una experiencia de caída libre indoor de 4 minutos acumulados',
  'Mantener vuelo estable 30 segundos en túnel de viento',
  'Subir 3 m en telas aéreas con técnica',
  'Hacer paracaidismo tándem desde más de 3.000 m',
  'Completar un curso de iniciación al parapente',
  'Conducir una moto de agua',
  'Hacer kayak de mar por primera vez',
  'Hacer paddle surf al amanecer',
  'Hacer paddle surf en un lago',
  'Hacer paddle surf por primera vez',
  'Hacer rafting nivel II',
  'Hacer snorkel durante una hora',
  'Mantenerte de pie 30 minutos en paddle surf',
  'Ponerte de pie en una ola de espuma',
  'Coger 10 olas en bodyboard',
  'Completar un bautismo de buceo',
  'Gobernar un velero durante una hora',
  'Hacer rafting nivel III',
  'Hacer snorkel en un arrecife',
  'Hacer surf',
  'Hacer un surf camp de una semana',
  'Hacer una ruta en moto de agua',
  'Mantenerte 5 minutos en esquí acuático',
  'Ponerte de pie en wakeboard',
  'Recorrer 10 km en kayak',
  'Recorrer 5 km en paddle surf',
  'Surfear 10 olas en una sesión',
  'Surfear una ola de 1 metro',
  'Surfear una ola verde',
  'Cruzar la estela en wakeboard',
  'Hacer 5 días de surf consecutivos',
  'Hacer surf en otro continente',
  'Hacer una inmersión desde barco',
  'Hacer una travesía costera en moto de agua',
  'Hacer una travesía de kayak de un día',
  'Hacer waterstart en kitesurf',
  'Navegar 1 km en windsurf',
  'Participar en una regata amateur',
  'Recorrer 10 km en paddle surf',
  'Surfear la ola sin cuerda en wakesurf',
  'Surfear una ola de 1,5 metros',
  'Hacer rafting nivel IV',
  'Hacer una inmersión nocturna',
  'Mantener vuelo estable 100 m en e-foil',
  'Ponerte de pie y navegar en wingfoil',
  'Surfear una ola de 2 metros con experiencia adecuada',
  'Completar clases de boxeo',
  'Completar 20 clases de kickboxing',
  'Completar 5 rounds de pads de Muay Thai',
  'Conseguir tu primera finalización técnica en rolling',
  'Ganar un asalto amistoso de esgrima',
  'Romper una tabla en una demostración',
  'Completar 50 sesiones de BJJ',
  'Completar un campamento de artes marciales de fin de semana',
  'Entrenar Muay Thai en Tailandia',
  'Hacer sparring técnico de Muay Thai',
  'Hacer tu primer sparring técnico de boxeo',
  'Participar en un interclub de boxeo amateur',
  'Participar en un torneo amateur de BJJ',
  'Anotar un triple en un partido',
  'Ganar un partido de pádel',
  'Completar 10 partidos de pádel en un mes',
  'Conseguir un hit en béisbol o softball',
  'Ganar un set de tenis',
  'Hacer 20 servicios de tenis válidos consecutivos',
  'Hacer un ace en un partido de tenis',
  'Hacer un saque directo en voleibol',
  'Marcar un gol en fútbol 11',
  'Participar en un torneo amateur de bádminton',
  'Participar en un torneo amateur de pádel',
  'Participar en un torneo amateur de vóley playa',
  'Anotar 10 tiros libres consecutivos',
  'Meter un hat-trick en un partido amateur',
  'Participar en un torneo amateur de tenis',
  'Hacer un mate en una canasta reglamentaria',
  'Subirte a un skateboard y avanzar con control',
  'Caminar 10 m sobre slackline',
  'Hacer un ollie en skateboard',
  'Hacer una ruta de 10 km en longboard',
  'Mantenerte 30 segundos sobre slackline',
  'Patinar en línea',
  'Bombear 1 km en surfskate sin empujar',
  'Caminar 30 m sobre slackline',
  'Completar 20 vueltas a un pump track',
  'Completar un circuito de parkour para principiantes',
  'Hacer un ollie sobre un obstáculo pequeño',
  'Hacer un kickflip',
  'Resolver un bloque de grado V',
  'Encadenar una vía deportiva de grado',
  'Encadenar una vía deportiva de grado 5a',
  'Encadenar una vía deportiva de grado 5b',
  'Encadenar una vía deportiva de grado 5c',
  'Encadenar una vía deportiva de grado 6a+',
  'Encadenar una vía deportiva de grado 6b+',
  'Escalar en granito',
  'Escalar en roca caliza',
  'Escalar una vía de varios largos',
  'Hacer una salida de escalada en roca',
  'Hacer una sesión de boulder de 2 horas',
  'Mantenerte segundos colgado de una barra',
  'Completar 20 bloques diferentes en una sesión',
  'Escalar de primero una vía fácil',
  'Completar una ruta de 5 largos',
  'Completar un AMRAP de 20 minutos',
  'Completar 100 burpees seguidos',
  'Completar rondas de air squats + push-ups + sit-ups',
  'Hacer tu primer box jump',
  'Hacer tu primer double-under',
  'Completar 50 box jumps sin fallos',
  'Hacer 50 double unders seguidos',
  'Hacer tu primer chest-to-bar',
  'Hacer tu primer rope climb',
  'Hacer tu primer toes-to-bar',
  'Completar un evento tipo DEKA',
  'Hacer 10 chest-to-bar seguidos',
  'Hacer 50 kettlebell swings seguidos',
  'Hacer tu primer bar muscle-up',
  'Hacer tu primer handstand push-up',
  'Hacer una competición por parejas',
  'Participar en una competición de fitness funcional',
  'Caminar 20 m haciendo handstand',
  'Completar un Hero WOD RX',
  'Completar un evento tipo HYROX',
  'Hacer 100 wall balls seguidos',
  'Hacer 5 bar muscle-ups seguidos',
  'Hacer tu primer ring muscle-up',
  'Hacer un Turkish get-up con 25% de tu peso corporal',
  'Subir una cuerda sin piernas',
  'Hacer 10 handstand push-ups seguidos',
  'Hacer 5 ring muscle-ups seguidos',
  'Acumular',
  'Completar de farmer carry con dos cargas del % de tu peso corporal',
  'Completar 50 m de bear hug carry con tu peso corporal',
  'Completar 50 m de suitcase carry con el 50% de tu peso corporal en una mano',
  'Levantar × tu peso corporal en press estricto para repetición',
  'Levantar × tu peso corporal en snatch para repetición',
  'Levantar × tu peso corporal en clean para repetición',
  'Levantar × tu peso corporal en press banca para repetición',
  'Levantar × tu peso corporal en sentadilla frontal para repetición',
  'Levantar × tu peso corporal en peso muerto para repetición',
  'Levantar × tu peso corporal en sentadilla trasera para repetición',
  'Levantar 1× tu peso corporal en clean para 1 repetición',
  'Levantar 1× tu peso corporal en press banca para 1 repetición',
  'Levantar 1× tu peso corporal en sentadilla frontal para 1 repetición',
  'Levantar 1× tu peso corporal en snatch para 1 repetición',
  'Levantar 1× tu peso corporal en press estricto para 1 repetición',
  'Hacer tu primera dominada estricta',
  'Mantener una plancha',
  'Completar 100 flexiones en una sesión',
  'Completar 100 sentadillas con peso corporal sin parar',
  'Completar 50 zancadas por pierna con peso corporal',
  'Hacer tu primer fondo en anillas',
  'Arrastrar un trineo pesado 100 m',
  'Empujar un trineo pesado 100 m',
  'Hacer tu primera dominada lastrada',
  'Completar una competición amateur de halterofilia',
  'Completar una competición amateur de powerlifting',
  'Hacer 10 fondos en anillas seguidos',
  'Hacer una dominada con % de tu peso corporal de lastre',
  'Realizar un levantamiento de atlas stone',
  'Alcanzar una cumbre de más de 3.000 m',
  'Completar una ruta de senderismo de 10 km en un día',
  'Completar una ruta de senderismo de 20 km en un día',
  'Completar una ruta de senderismo de 40 km en un día',
  'Dormir en un refugio de montaña',
  'Completar una ruta de orientación con mapa y brújula',
  'Hacer una ruta con raquetas de nieve',
  'Hacer una vía ferrata nivel fácil',
  'Ver un amanecer desde una cumbre',
  'Caminar 50.000 pasos en un día',
  'Completar una ruta sin usar GPS, con mapa y brújula',
  'Cruzar un puente tibetano en una vía ferrata',
  'Dormir en vivac donde esté permitido',
  'Hacer trekking en un desierto',
  'Hacer trekking en una selva',
  'Hacer una vía ferrata nivel medio',
  'Ver un atardecer desde una cumbre y descender con frontal',
  'Aprender autodetención con piolet en curso',
  'Completar un camino de peregrinación de 100 km',
  'Hacer una marcha de 12 horas',
  'Hacer una ruta circular alrededor de un macizo',
  'Hacer una ruta glaciar',
  'Hacer una vía ferrata difícil',
  'Caminar 100.000 pasos en 24 horas',
  'Completar una travesía de montaña de días',
  'Conducir un quad en una ruta',
  'Ganar una carrera amateur de karting',
  'Hacer canyoning nivel iniciación',
  'Hacer tirolina de más de 500 m',
  'Hacer una ruta de buggy off-road',
  'Hacer una ruta de quad por montaña autorizada',
  'Hacer una ruta larga en moto de más de 300 km',
  'Volar en túnel de viento',
  'Completar un curso de conducción off-road',
  'Completar una carrera Spartan Sprint',
  'Conducir un coche deportivo en circuito',
  'Hacer ala delta biplaza',
  'Hacer canyoning nivel intermedio',
  'Hacer coasteering',
  'Hacer parapente biplaza',
  'Hacer una jornada de enduro en circuito',
  'Hacer una tanda de karting de resistencia de 1 hora por equipos',
  'Hacer una tirolina de más de 1 km',
  'Completar una Spartan Super',
  'Completar una Tough Mudder',
  'Hacer paracaidismo tándem',
  'Hacer una experiencia de rally',
  'Hacer una ruta de moto de más de 1.000 km en varios días',
  'Hacer una tanda de track day como conductor',
  'Rodar en circuito con una moto bajo formación',
  'Completar un curso de iniciación al paracaidismo',
  'Completar una Spartan Beast',
  'Nadar 100 m crol',
  'Nadar 500 metros sin parar',
  'Nadar 1000 m',
  'Nadar',
  'Nadar 500 m en piscina',
  'Nadar 1000 m en piscina',
  'Nadar 500 m en aguas abiertas',
  'Nadar 500 m en el mar',
  'Nadar 500 m en un lago',
  'Nadar 1000 m en aguas abiertas',
  'Nadar 1000 m en el mar',
  'Nadar 1000 m en un lago',
  'Nadar 5000 m en piscina',
  'Nadar 5000 m en aguas abiertas',
  'Nadar 5000 m en el mar',
  'Nadar 5000 m en un lago',
  'Hacer una apnea estática de 60 segundos en entorno seguro',
  'Hacer una sesión de técnica con palas, pull buoy y aletas',
  'Nadar con neopreno en aguas abiertas',
  'Nadar 1.000 metros en piscina',
  'Completar una travesía popular en aguas abiertas',
  'Hacer 20 virajes perfectos seguidos',
  'Hacer una sesión de natación de 90 minutos',
  'Nadar 400 m respirando cada 3 brazadas',
  'Nadar sin neopreno en agua templada durante 30 minutos',
  'Hacer 25 m subacuáticos solo en entrenamiento',
  'Nadar de noche en un evento organizado',
  'Nadar 100 m de braza sin detenerse',
  'Nadar 100 m de crol sin detenerse',
  'Nadar 100 m de espalda sin detenerse',
  'Nadar 100 m de mariposa sin detenerse',
  'Bajar una pista verde con control',
  'Esquiar por primera vez',
  'Bajar una pista azul con control',
  'Bajar una pista azul en snowboard',
  'Completar de esquí de fondo',
  'Esquiar 50 km en un día',
  'Hacer un curso de técnica de carving',
  'Hacer un giro enlazado en snowboard',
  'Hacer una jornada de esquí al amanecer',
  'Hacer una ruta con raquetas de nieve de 10 km',
  'Patinar 5 km sobre pista de hielo',
  'Bajar una pista roja con control',
  'Entrar en un snowpark y completar una línea fácil',
  'Esquiar durante 5 días consecutivos',
  'Hacer un ollie en snowboard',
  'Bajar una pista negra con control',
  'Hacer una jornada de esquí de travesía',
  'Subir 500 m de desnivel con esquís de travesía',
  'Subir 1.000 m de desnivel con esquís de travesía',
  'Completar un arrastre de saco de 100 m',
  'Completar un circuito ninja para principiantes',
  'Completar una carrera de obstáculos',
  'Completar una carrera de barro',
  'Subir una cuerda de 5 m',
  'Superar una monkey bar completa',
  'Trepar un muro de 2 m',
  'Completar un farmer carry de carrera OCR de 200 m',
  'Cruzar una monkey bar de 10 m',
  'Hacer una carrera OCR por equipos',
  'Superar 10 obstáculos sin penalización',
  'Trepar un muro de 2,5 m con técnica',
  'Completar 5 obstáculos ninja consecutivos',
  'Completar una carga de sandbag de 1 km',
  'Completar una carrera OCR en invierno',
  'Completar una carrera OCR nocturna',
  'Superar una warped wall',
  'Completar una trifecta de tres distancias OCR en un año',
  'Hacer geocaching durante una jornada',
  'Hacer una ruta en camello por dunas',
  'Montar a caballo por primera vez',
  'Completar 20 km de marcha nórdica',
  'Encontrar 20 geocachés en un día',
  'Hacer una ruta a caballo de 2 horas',
  'Hacer una ruta en trineo de perros responsable',
  'Completar una carrera de orientación en bosque',
  'Hacer una ruta a caballo de día completo',
  'Participar en una prueba de salvamento y socorrismo deportivo',
  'Completar una carrera rogaining de horas',
  'Hacer malabares con 3 pelotas durante 1 minuto',
  'Mantener un diábolo girando 2 minutos',
  'Agrupar 5 flechas dentro de un círculo de 20 cm a 10 m',
  'Cerrar una partida de dardos con un doble',
  'Hacer 50 toques alternando ambos pies',
  'Hacer malabares con 3 pelotas durante 5 minutos',
  'Hacer un par en un hoyo de golf',
  'Meter 20 triples en una sesión de 100 intentos',
  'Acertar una diana a 30 m con arco en campo',
  'Bajar de golpes en hoyos',
  'Encestar 10 tiros libres seguidos',
  'Hacer 100 toques de balón de fútbol sin que caiga',
  'Hacer un birdie',
  'Participar en una competición amateur de tiro con arco',
  'Hacer una serie de 10 bolas seguidas en billar de entrenamiento',
  'Superar 200 puntos en bolos',
  'Hacer un 180 en dardos',
  'Hacer un hoyo en uno',
  'Remar en agua',
  'Participar en una regata amateur de remo',
  'Remar en ergómetro',
  'Remar de forma continua durante en ergómetro',
  'Correr 10 km',
  'Correr 5 km',
  'Correr al menos 5 km durante 7 días consecutivos',
  'Acumular 1.000 m de desnivel corriendo',
  'Correr una media maratón',
  'Correr',
  'Correr una maratón',
  'Correr 100 km sin parar',
  'Correr por una causa benéfica',
  'Correr una carrera vestido con un disfraz',
  'Correr una milla urbana',
  'Hacer un parkrun en otro país',
  'Participar en una San Silvestre',
  'Completar una carrera de orientación urbana',
  'Correr una carrera de obstáculos',
  'Correr una carrera en una capital europea',
  'Correr una carrera nocturna',
  'Hacer de pacer a un amigo en una carrera',
  'Participar en una carrera de relevos',
  'Completar una carrera vertical de escaleras',
  'Completar un 24 horas por relevos',
  'Completar un kilómetro vertical',
  'Correr un backyard ultra durante al menos 6 vueltas',
  'Completar un trail de 10 km',
  'Completar un trail de 42 km',
  'Completar una sesión combinada de 2 km remo + 5 km carrera sin pausa larga',
  'Completar una sesión combinada de bici + carrera sin pausa larga',
  'Completar una sesión combinada de carrera + bici sin pausa larga',
  'Completar una sesión combinada de 500 m natación + 20 km bici sin pausa larga',
  'Completar una sesión combinada de 1 km natación + 5 km carrera sin pausa larga',
  'Completar una sesión combinada de 5 km SkiErg + 5 km carrera sin pausa larga',
  'Completar una sesión combinada de 1,5 km natación + 10 km carrera sin pausa larga',
  'Hacer un triatlón por relevos',
  'Participar en un aquatlón',
  'Participar en un duatlón sprint',
  'Completar tu primer triatlón sin objetivo de tiempo',
  'Completar un duatlón estándar',
  'Completar un swimrun corto',
  'Completar una carrera de orientación por equipos',
  'Hacer un entrenamiento triple: remo + bici + carrera',
  'Hacer un triatlón con salida desde playa',
  'Completar un reto de 4 deportes en un día',
  'Completar un triatlón de montaña',
  'Hacer una competición de adventure race',
  'Completar un swimrun de más de 20 km',
  'Hacer 1 hora de natación, 2 de bici y 1 de carrera en un mismo día',
  'Practicar transiciones completas de triatlón',
  'Completar un triatlón Super sprint: 400 m natación + 10 km bici + 2,5 km carrera',
  'Completar un triatlón Sprint: 750 m natación + 20 km bici + 5 km carrera',
  'Completar un triatlón Olímpico: 1,5 km natación + 40 km bici + 10 km carrera',
  'Completar un triatlón Half: 1,9 km natación + 90 km bici + 21,1 km carrera',
  'Completar un triatlón Ironman: 3,8 km natación + 180 km bici + 42,2 km carrera',
  'Hacer 10 flexiones seguidas',
  'Hacer 50 flexiones seguidas',
  'Hacer 100 flexiones seguidas',
  'Hacer 5 dominadas seguidas',
  'Hacer 10 dominadas seguidas',
  'Hacer 20 dominadas seguidas',
  'Hacer una dominada con peso añadido de 20 kg',
  'Hacer un muscle up',
  'Hacer 5 muscle ups seguidos',
  'Hacer 10 fondos en anillas',
  'Hacer 10 toes to bar',
  'Aguantar un pino de 30 segundos',
  'Hacer 10 metros de handstand walk',
  'Hacer una flexión a pino',
  'Aguantar una bandera humana 5 segundos',
  'Aguantar un back lever completo 5 segundos',
  'Aguantar un front lever completo 5 segundos',
  'Aguantar una plancha de 3 minutos',
  'Hacer un snatch de 50 kg',
  'Hacer un snatch de 80 kg',
  'Hacer un snatch de 100 kg',
  'Hacer un clean & jerk de 50 kg',
  'Hacer un clean & jerk de 80 kg',
  'Hacer un clean & jerk de 100 kg',
  'Aprender la técnica de los dos levantamientos olímpicos',
  'Hacer press banca con 40 kg',
  'Hacer press banca con 60 kg',
  'Hacer press banca con 80 kg',
  'Hacer press banca con 100 kg',
  'Hacer press banca con 120 kg',
  'Hacer sentadilla con 60 kg',
  'Hacer sentadilla con 100 kg',
  'Hacer sentadilla con 140 kg',
  'Hacer sentadilla con 180 kg',
  'Hacer peso muerto con 80 kg',
  'Hacer peso muerto con 120 kg',
  'Hacer peso muerto con 160 kg',
  'Hacer peso muerto con 200 kg',
  'Levantar tu propio peso en press banca',
  'Levantar el doble de tu peso en peso muerto',
  'Competir en una prueba de halterofilia',
  'Competir en una prueba de powerlifting',
  'Completar un Hyrox',
  'Competir en unos Open de CrossFit',
  'Completar un Murph completo con chaleco',
  'Competir en una prueba de escalada en bloque',
  'Jugar al tenis',
  'Jugar al pádel',
  'Jugar al bádminton',
  'Jugar al squash',
  'Jugar al ping-pong',
  'Jugar al pickleball',
  'Jugar al frontón',
  'Jugar un partido de fútbol',
  'Jugar al fútbol sala',
  'Jugar al fútbol playa',
  'Jugar al baloncesto',
  'Jugar al balonmano',
  'Jugar al voleibol',
  'Jugar al vóley playa',
  'Jugar al rugby',
  'Jugar al fútbol americano',
  'Jugar al hockey sobre hierba',
  'Jugar al hockey sobre hielo',
  'Jugar al béisbol',
  'Jugar al críquet',
  'Jugar al waterpolo',
  'Jugar al ultimate frisbee',
  'Jugar al golf',
  'Jugar a los bolos',
  'Jugar al billar',
  'Jugar a los dardos',
  'Jugar al curling',
  'Hacer bodyboard',
  'Hacer paddle surf',
  'Hacer windsurf',
  'Hacer kitesurf',
  'Hacer wakeboard',
  'Hacer esquí acuático',
  'Hacer wingfoil',
  'Navegar a vela',
  'Salir a remar',
  'Hacer kayak',
  'Hacer piragüismo',
  'Nadar en aguas abiertas',
  'Bucear con botella',
  'Hacer snorkel',
  'Hacer apnea',
  'Pilotar una moto de agua',
  'Esquiar',
  'Hacer snowboard',
  'Hacer esquí de fondo',
  'Hacer esquí de montaña',
  'Patinar sobre hielo',
  'Bajar en trineo',
  'Caminar con raquetas de nieve',
  'Escalar en rocódromo',
  'Escalar en roca',
  'Hacer boulder',
  'Hacer una vía ferrata',
  'Hacer senderismo',
  'Correr por montaña',
  'Hacer montañismo',
  'Hacer barranquismo',
  'Hacer espeleología',
  'Caminar por una slackline',
  'Salir en bicicleta de carretera',
  'Salir en bicicleta de montaña',
  'Salir en gravel',
  'Montar en BMX',
  'Montar en patines en línea',
  'Montar en monopatín',
  'Montar en longboard',
  'Hacer parkour',
  'Correr en karts',
  'Hacer motocross',
  'Hacer enduro',
  'Conducir en circuito',
  'Conducir un 4x4 fuera de asfalto',
  'Montar en quad',
  'Hacer una ruta larga en moto',
  'Practicar boxeo',
  'Practicar muay thai o kickboxing',
  'Practicar judo',
  'Practicar kárate',
  'Practicar taekwondo',
  'Practicar jiu-jitsu brasileño',
  'Practicar lucha',
  'Practicar esgrima',
  'Practicar capoeira',
  'Entrenar crossfit',
  'Entrenar halterofilia',
  'Entrenar powerlifting',
  'Entrenar calistenia',
  'Hacer yoga',
  'Hacer pilates',
  'Correr una carrera popular',
  'Entrenar en una pista de atletismo',
  'Montar a caballo',
  'Jugar al polo',
  'Tirar con arco',
  'Hacer orientación con mapa y brújula',
  'Salir a pescar',
  'Volar en un túnel de viento',
  'Saltar en cama elástica',
  'Hacer gimnasia artística',
  'Hacer trapecio o acrobacia aérea'
  )
  and not exists (select 1 from user_gooals u where u.gooal_id = g.id);

-- ── aventura (225 títulos buenos) ──
delete from gooals_v2 g
where g.categoria = 'aventura'
  and g.titulo not in (
  'Saltar en paracaídas en tándem',
  'Paracaidismo sobre el Everest desde gran altitud',
  'Salto BASE tandem autorizado desde Kjerag',
  'Hacer puenting desde un puente o una presa',
  'Lanzarse en un swing gigante sobre un cañón',
  'Volar en parapente en tándem',
  'Volar en ala delta en tándem',
  'Vuelo en globo sobre Capadocia',
  'Volar en globo al amanecer',
  'Vuelo en globo sobre Serengeti',
  'Vuelo acrobatico en avion',
  'Vuelo en planeador sobre los Alpes',
  'Vuelo en hidroavion sobre Vancouver',
  'Sobrevolar un paisaje en helicóptero',
  'Cruzar un valle en tirolina',
  'Viajar en avion de bush y aterrizar en pista remota',
  'Rafting en el rio Zambeze bajo Victoria Falls',
  'Hacer rafting en aguas bravas',
  'Hacer kayak entre icebergs',
  'Hacer kayak de mar en una travesía guiada',
  'Kayak nocturno en bahia bioluminiscente',
  'Hacer descenso de barrancos',
  'Hacer coasteering en una costa rocosa',
  'Hydrospeed en un rio de aguas bravas',
  'Riverboarding en Nueva Zelanda',
  'Aprender kitesurf y navegar solo',
  'Navegar en windsurf con viento fuerte',
  'Aprender wingfoil',
  'Pilotar una moto de agua en una ruta costera',
  'Montar en jet boat por un cañón fluvial',
  'Flyboard sobre el mar',
  'Parasailing sobre una bahia tropical',
  'Esqui acuatico',
  'Kneeboard',
  'Tubing rapido detras de lancha',
  'Bucear en la Gran Barrera de Coral',
  'Bucear en un arrecife tropical',
  'Bucear en Galapagos',
  'Bucear en Blue Hole',
  'Bucear en cenotes de Yucatan',
  'Bucear en Silfra entre placas tectonicas',
  'Bucear con mantarrayas',
  'Bucear con tiburones ballena',
  'Bucear con tiburones martillo',
  'Bucear con tiburones toro',
  'Bucear con tiburones tigre',
  'Bucear en un pecio',
  'Bucear bajo hielo',
  'Completar certificacion Open Water',
  'Completar certificacion Advanced Open Water',
  'Completar curso Rescue Diver',
  'Hacer una inmersion profunda de 30 m',
  'Hacer una inmersion desde barco liveaboard',
  'Pasar una semana en liveaboard de buceo',
  'Snorkel con orcas bajo regulacion local',
  'Snorkel con tiburon ballena',
  'Snorkel con mantarrayas de noche',
  'Snorkel en cenote',
  'Freediving hasta 10 m con seguridad',
  'Freediving hasta 20 m con entrenamiento',
  'Completar curso de apnea nivel 1',
  'Completar curso de apnea nivel 2',
  'Nadar en una laguna bioluminiscente',
  'Nadar con leones marinos',
  'Nadar con delfines en entorno silvestre regulado',
  'Nadar con tortugas marinas',
  'Nadar con rayas en aguas abiertas',
  'Hacer shark cage diving',
  'Hacer shark cage diving con grandes blancos donde este permitido',
  'Explorar una cueva submarina solo',
  'Completar una vía ferrata',
  'Escalar una via deportiva de grado inicial',
  'Escalar en roca en una zona clásica',
  'Escalar una cascada de hielo',
  'Ascender el Kilimanjaro',
  'Ascender el Toubkal',
  'Ascender el Teide a pie',
  'Ascender el Mulhacen',
  'Ascender el Aneto',
  'Ascender Monte Perdido',
  'Ascender el Mont Blanc',
  'Ascender el Gran Paradiso',
  'Ascender el Triglav',
  'Ascender el Olympus',
  'Ascender el Fuji',
  'Ascender el Rinjani',
  'Ascender el Kinabalu',
  'Ascender el Acatenango y ver Fuego',
  'Ascender el Cotopaxi con aclimatacion',
  'Ascender el Chimborazo',
  'Ascender el Huayna Potosi',
  'Ascender el Aconcagua',
  'Ascender el Elbrus',
  'Ascender el Damavand',
  'Ascender el Kazbek',
  'Ascender el Island Peak',
  'Ascender Mera Peak',
  'Llegar al Everest Base Camp',
  'Completar el Annapurna Circuit',
  'Completar el Tour du Mont Blanc',
  'Completar el GR20',
  'Completar el Laugavegur Trail',
  'Completar el W Trek',
  'Completar el O Circuit',
  'Completar Huayhuash Circuit',
  'Completar Alta Via 1',
  'Completar West Highland Way',
  'Completar Camino Inca a Machu Picchu',
  'Cruzar el Tongariro Alpine Crossing',
  'Hacer el Mount Rinjani trek',
  'Subir a un volcán a ver el amanecer',
  'Hacer trekking al Tiger''s Nest',
  'Hacer un trekking de varios días en montaña',
  'Hacer trekking en Patagonia sobre hielo',
  'Esquiar una jornada completa en estación',
  'Esquiar un día de nieve polvo',
  'Bajar una pista completa en snowboard',
  'Aprender un 180 en snowboard',
  'Aprender un salto basico en snowpark',
  'Hacer una jornada de freeride',
  'Hacer heliesquí con guía',
  'Hacer una travesía de esquí de montaña',
  'Caminar sobre un glaciar con crampones',
  'Conducir una moto de nieve',
  'Guiar un trineo de perros',
  'Dormir en un campamento de nieve tras llegar con raquetas',
  'Hacer una travesia con raquetas de nieve',
  'Bañarse en agua helada',
  'Explorar una cueva de hielo natural',
  'Conducir un quad o buggy por dunas',
  'Bajar una duna en sandboard',
  'Cruzar un desierto en 4x4',
  'Hacer una ruta 4x4 por el Salar de Uyuni',
  'Conducir por pistas del interior de Islandia con 4x4',
  'Ruta enduro',
  'Ruta de motocross en circuito',
  'Curso de conduccion 4x4',
  'Curso de conduccion sobre hielo',
  'Conducir un coche de rally en circuito',
  'Copilotar un coche de rally',
  'Conducir un superdeportivo en circuito',
  'Rodar en un circuito de F1 con instructor',
  'Pilotar un kart de competicion',
  'Participar en una carrera amateur de karting',
  'Hacer una ruta de varios días en moto',
  'Cruzar un puerto alpino en moto',
  'Safari fotografico en Serengeti durante la migracion',
  'Hacer un safari en vehículo',
  'Safari a pie con ranger',
  'Safari nocturno',
  'Rastrear gorilas de montana',
  'Rastrear chimpances',
  'Ver orangutanes en Borneo',
  'Ver osos polares con expedicion autorizada',
  'Ver osos grizzly',
  'Ver lobos en Yellowstone',
  'Ver ballenas jorobadas desde kayak',
  'Ver orcas en libertad',
  'Ver ballena azul en libertad',
  'Ver pinguinos emperador en expedicion polar',
  'Ver pinguinos rey',
  'Ver pinguinos africanos',
  'Visitar Komodo con ranger',
  'Navegar por el Amazonas y dormir en lodge selvatico',
  'Caminar por selva amazonica',
  'Expedicion por Borneo',
  'Expedicion por Papua',
  'Dormir en la selva de Costa Rica',
  'Cruzar un puente colgante sobre canopy tropical',
  'Hacer rafting y trekking en selva de Ecuador',
  'Explorar manglares en bote pequeno',
  'Hacer una expedicion de varios dias en canoa',
  'Cruzar un desierto a camello',
  'Dormir en el desierto bajo las estrellas',
  'Expedicion al Danakil autorizado',
  'Visitar un volcan activo desde zona segura',
  'Subir a un volcan y ver lava desde distancia permitida',
  'Explorar un tubo o campo de lava',
  'Visitar el crater de Nyiragongo cuando sea seguro y abierto',
  'Trekking por Kamchatka',
  'Expedicion a Svalbard en barco',
  'Cruzar el Circulo Polar Artico por tierra',
  'Viajar a la Antartida en expedicion',
  'Desembarcar en la peninsula Antartica',
  'Hacer kayak en la Antartida',
  'Acampar una noche en la Antartida si la expedicion lo permite',
  'Cruzar el Drake Passage',
  'Expedicion a Georgia del Sur',
  'Expedicion a Groenlandia oriental',
  'Trekking sobre tundra en Groenlandia',
  'Dormir en tienda bajo auroras boreales',
  'Perseguir auroras boreales durante varios dias',
  'Ver el sol de medianoche sobre el Artico',
  'Explorar Son Doong con expedicion autorizada',
  'Explorar Hang En Cave',
  'Descender a Waitomo y hacer black-water rafting',
  'Explorar una cueva turística de gran formato',
  'Hacer espeleología deportiva',
  'Explorar una mina abandonada para visitas de aventura',
  'Descender con rapel a una sima',
  'Hacer un curso basico de espeleologia',
  'Hacer rapel de 50 m',
  'Hacer rapel en cascada',
  'Hacer un pendulo gigante desde puente autorizado',
  'Caminar por el borde exterior de un rascacielos',
  'Subir por escaleras exteriores de un rascacielos',
  'Hacer parkour en entorno urbano',
  'Probar trampolin freestyle',
  'Completar un ninja warrior course',
  'Completar una carrera de obstaculos con barro',
  'Completar una carrera Tough Mudder',
  'Completar una Spartan Sprint',
  'Completar una Spartan Trifecta',
  'Participar en una carrera de orientacion de aventura',
  'Hacer geocaching en un entorno remoto',
  'Completar una ruta de orientacion sin GPS',
  'Hacer supervivencia 24 h',
  'Hacer supervivencia 48 h',
  'Aprender a encender fuego y construir refugio en curso bushcraft',
  'Dormir una noche en vivac de montana',
  'Dormir en hamaca en selva',
  'Cruzar un puente tibetano de gran altura',
  'Completar un circuito de cuerdas a gran altura',
  'Probar un simulador de caida libre indoor',
  'Aprender maniobras basicas de bodyflight'
  )
  and not exists (select 1 from user_gooals u where u.gooal_id = g.id);

-- ── cultura (437 títulos buenos) ──
delete from gooals_v2 g
where g.categoria = 'cultura'
  and g.titulo not in (
  'Visitar el Museo del Louvre',
  'Visitar Musee d''Orsay',
  'Visitar Centre Pompidou',
  'Visitar Museo Reina Sofia',
  'Visitar Museo Thyssen-Bornemisza',
  'Visitar Guggenheim Bilbao',
  'Visitar Museu Nacional d''Art de Catalunya',
  'Visitar Museu Picasso',
  'Visitar Fundacio Joan Miro',
  'Visitar Uffizi',
  'Visitar Galleria dell''Accademia',
  'Visitar Museos Vaticanos',
  'Visitar Galleria Borghese',
  'Visitar Museo Arqueologico Nacional de Napoles',
  'Visitar Peggy Guggenheim Collection',
  'Visitar Pinacoteca di Brera',
  'Visitar National Gallery',
  'Visitar Tate Modern',
  'Visitar Victoria and Albert Museum',
  'Visitar Natural History Museum',
  'Visitar Van Gogh Museum',
  'Visitar Kunsthistorisches Museum',
  'Visitar Albertina',
  'Visitar Belvedere',
  'Visitar Pergamonmuseum cuando este plenamente accesible',
  'Visitar Neues Museum',
  'Visitar Alte Nationalgalerie',
  'Visitar Gemäldegalerie',
  'Visitar Museum Ludwig',
  'Visitar Städel Museum',
  'Visitar National Museum · República Checa',
  'Visitar Museum of Communism',
  'Visitar Hungarian National Gallery',
  'Visitar Museum of Fine Arts',
  'Visitar National Museum in Krakow',
  'Visitar POLIN Museum',
  'Visitar National Museum of Denmark',
  'Visitar Louisiana Museum of Modern Art',
  'Visitar Nationalmuseum',
  'Visitar Munch Museum',
  'Visitar National Museum · Noruega',
  'Visitar Ateneum',
  'Visitar Hermitage Museum',
  'Visitar Tretyakov Gallery',
  'Visitar Acropolis Museum',
  'Visitar National Archaeological Museum',
  'Visitar Istanbul Archaeology Museums',
  'Visitar Museum of Turkish and Islamic Arts',
  'Visitar Museum of Anatolian Civilizations',
  'Visitar Georgian National Museum',
  'Visitar Matenadaran',
  'Visitar Israel Museum',
  'Visitar Grand Egyptian Museum',
  'Visitar Museum of Islamic Art',
  'Visitar National Museum of African American History and Culture',
  'Visitar Smithsonian National Air and Space Museum',
  'Visitar National Gallery of Art',
  'Visitar Metropolitan Museum of Art',
  'Visitar Museum of Modern Art',
  'Visitar Whitney Museum',
  'Visitar Guggenheim New York',
  'Visitar American Museum of Natural History',
  'Visitar Art Institute of Chicago',
  'Visitar Getty Center',
  'Visitar LACMA',
  'Visitar SFMOMA',
  'Visitar de Young Museum',
  'Visitar Museum of Anthropology',
  'Visitar Royal Ontario Museum',
  'Visitar Art Gallery of Ontario',
  'Visitar Montreal Museum of Fine Arts',
  'Visitar Museo Frida Kahlo',
  'Visitar Museo Soumaya',
  'Visitar Museo de Arte Moderno',
  'Visitar Museo Larco',
  'Visitar MALI',
  'Visitar Museo del Oro',
  'Visitar Museo Botero',
  'Visitar MALBA',
  'Visitar Museo Nacional de Bellas Artes',
  'Visitar Museu de Arte de Sao Paulo',
  'Visitar Pinacoteca de Sao Paulo',
  'Visitar Museo de la Memoria y los Derechos Humanos',
  'Visitar Museo Chileno de Arte Precolombino',
  'Visitar National Museum of China',
  'Visitar Palace Museum en Forbidden City',
  'Visitar Shanghai Museum',
  'Visitar Hong Kong Museum of History',
  'Visitar M+',
  'Visitar Tokyo National Museum',
  'Visitar Mori Art Museum',
  'Visitar teamLab Borderless',
  'Visitar National Museum of Modern Art',
  'Visitar Kyoto National Museum',
  'Visitar Hiroshima Peace Memorial Museum',
  'Visitar National Museum of Korea',
  'Visitar Leeum Museum of Art',
  'Visitar War Memorial of Korea',
  'Visitar National Museum of Singapore',
  'Visitar Asian Civilisations Museum',
  'Visitar Museum of Islamic Arts',
  'Visitar National Museum Bangkok',
  'Visitar Museum of Ethnology',
  'Visitar National Museum of Indonesia',
  'Visitar Museum Pasifika',
  'Visitar National Museum of the Philippines',
  'Visitar National Museum New Delhi',
  'Visitar Indian Museum',
  'Visitar Chhatrapati Shivaji Maharaj Vastu Sangrahalaya',
  'Visitar National Museum Colombo',
  'Visitar Nepal National Museum',
  'Visitar National Gallery of Victoria',
  'Visitar Australian Museum',
  'Visitar Art Gallery of New South Wales',
  'Visitar MONA',
  'Visitar Museum of New Zealand Te Papa Tongarewa',
  'Visitar Auckland War Memorial Museum',
  'Visitar Zeitz MOCAA',
  'Visitar Apartheid Museum',
  'Visitar Robben Island Museum',
  'Recorrer la Acropolis y el Partenon',
  'Visitar Olimpia antigua',
  'Visitar Knossos',
  'Visitar Herculano',
  'Recorrer el Foro Romano',
  'Visitar Ostia Antica',
  'Visitar Paestum',
  'Recorrer Hadrian''s Wall',
  'Visitar Skara Brae',
  'Visitar Carnac',
  'Visitar Lascaux IV',
  'Visitar Altamira y su museo',
  'Visitar Atapuerca',
  'Visitar Merida romana',
  'Visitar Tarragona romana',
  'Visitar Medina Azahara',
  'Visitar la Alhambra con visita historica completa',
  'Recorrer Toledo historico',
  'Recorrer Segovia y su acueducto',
  'Visitar Conimbriga',
  'Recorrer Dubrovnik historico',
  'Visitar Diocletian''s Palace',
  'Visitar Mostar y su patrimonio otomano',
  'Visitar monasterios de Meteora',
  'Visitar Troya',
  'Visitar Göbekli Tepe',
  'Visitar Hattusa',
  'Visitar Nemrut Dagi',
  'Visitar Ani',
  'Recorrer Jerash',
  'Visitar Quseir Amra',
  'Recorrer Wadi Rum desde perspectiva historica beduina',
  'Visitar Baalbek',
  'Visitar Byblos',
  'Recorrer la Ciudad Vieja de Jerusalen',
  'Visitar Karnak',
  'Visitar Valle de los Reyes',
  'Visitar Saqqara',
  'Visitar las Piramides de Giza',
  'Visitar Dendera',
  'Visitar Philae',
  'Visitar Dougga',
  'Visitar Cartago',
  'Visitar Leptis Magna cuando las condiciones lo permitan',
  'Visitar Lalibela',
  'Visitar Aksum',
  'Visitar Mapungubwe',
  'Visitar las iglesias rupestres de Tigray seguro',
  'Visitar la isla de Goree',
  'Visitar Timbuktu cuando las condiciones de seguridad lo permitan',
  'Visitar Monte Alban',
  'Visitar Tulum arqueologico',
  'Visitar Calakmul',
  'Visitar Copan',
  'Visitar Joya de Ceren',
  'Visitar Caral',
  'Sobrevolar o contemplar las Lineas de Nazca desde mirador autorizado',
  'Visitar Rapa Nui y sus moai',
  'Visitar San Agustin',
  'Visitar Ciudad Perdida con trekking',
  'Visitar Mesa Verde',
  'Visitar Chaco Culture',
  'Visitar Cahokia Mounds',
  'Visitar Taos Pueblo',
  'Visitar L''Anse aux Meadows',
  'Visitar Angkor Wat al amanecer',
  'Visitar Angkor Thom y Bayon',
  'Visitar Hue Imperial City',
  'Visitar Bagan',
  'Visitar Ayutthaya',
  'Visitar Sukhothai',
  'Visitar Polonnaruwa',
  'Visitar Anuradhapura',
  'Visitar Khajuraho',
  'Visitar Fatehpur Sikri',
  'Visitar Sanchi',
  'Visitar Mahabalipuram',
  'Visitar Konark Sun Temple',
  'Recorrer un tramo historico de la Gran Muralla',
  'Visitar Mogao Caves',
  'Visitar Longmen Grottoes',
  'Visitar Yungang Grottoes',
  'Visitar Nikko temples and shrines',
  'Visitar Nara y Todai-ji',
  'Visitar Nan Madol',
  'Entrar en Sagrada Familia y entender su simbolismo',
  'Recorrer las principales obras de Gaudi',
  'Visitar Catedral de Sevilla y Giralda',
  'Visitar Mezquita-Catedral de Cordoba',
  'Visitar Monasterio de El Escorial',
  'Visitar Sainte-Chapelle',
  'Visitar Notre-Dame de Paris',
  'Visitar Catedral de Chartres',
  'Visitar Basilica de Saint-Denis',
  'Subir a la cupula de San Pedro',
  'Visitar Duomo de Florencia',
  'Subir a la cupula de Brunelleschi',
  'Visitar Duomo de Milan y sus terrazas',
  'Visitar Basilica de San Marcos',
  'Visitar Basilica de San Francisco de Asis',
  'Visitar Catedral de Aquisgran',
  'Visitar Frauenkirche de Dresde',
  'Visitar Stephansdom',
  'Visitar Westminster Abbey',
  'Visitar St Paul''s Cathedral',
  'Visitar Canterbury Cathedral',
  'Visitar Rosslyn Chapel',
  'Visitar Trinity College y su biblioteca',
  'Visitar Parlamento de Budapest por dentro',
  'Visitar Matthias Church',
  'Visitar Iglesia de Santa Maria',
  'Visitar iglesias pintadas de Bucovina',
  'Visitar Iglesia de Boyana',
  'Visitar Catedral de Alexander Nevsky',
  'Visitar Mezquita de Suleymaniye',
  'Visitar Mezquita de Selimiye',
  'Visitar monasterio de Geghard',
  'Visitar monasterio de Tatev',
  'Visitar Imam Mosque',
  'Visitar Nasir al-Mulk Mosque',
  'Visitar Persepolis desde enfoque arquitectonico',
  'Visitar Dome of the Rock exterior y entorno segun acceso',
  'Visitar Monasterio de Santa Catalina',
  'Visitar Great Mosque of Kairouan',
  'Visitar Djenné Great Mosque desde el exterior y segun acceso local',
  'Visitar Rock-Hewn Churches de Lalibela',
  'Visitar Basilica of Our Lady of Peace',
  'Visitar Templo de Oro',
  'Visitar Taj Mahal al amanecer',
  'Visitar Jama Masjid',
  'Visitar Brihadeeswarar Temple',
  'Visitar Ranakpur Jain Temple',
  'Visitar Akshardham',
  'Visitar Tiger''s Nest',
  'Visitar Shwedagon Pagoda',
  'Visitar Wat Rong Khun',
  'Visitar Fushimi Inari',
  'Visitar Bulguksa',
  'Visitar Jogyesa',
  'Visitar Jokhang Temple',
  'Visitar Thean Hou Temple',
  'Visitar Sultan Mosque',
  'Visitar Besakih Temple',
  'Visitar Ulun Danu Beratan',
  'Visitar San Agustin Church',
  'Visitar Sydney Opera House con tour arquitectonico',
  'Visitar Maori meeting house y aprender protocolo marae',
  'Asistir a Semana Santa en Sevilla',
  'Vivir Feria de Abril',
  'Ver castellers en una diada',
  'Vivir Patum de Berga',
  'Asistir a Carnaval de Cadiz',
  'Vivir Carnaval de Santa Cruz de Tenerife',
  'Asistir a una mascleta',
  'Vivir Carnaval de Venecia',
  'Asistir al Palio di Siena',
  'Vivir Infiorata en una ciudad italiana',
  'Asistir a una representacion en Arena di Verona',
  'Vivir Oktoberfest desde su tradicion bávara',
  'Vivir un mercado navideño historico',
  'Asistir a Viena Opera Ball o un gran baile tradicional',
  'Escuchar Concierto de Año Nuevo en Viena si se logra entrada',
  'Vivir Edinburgh Festival Fringe',
  'Asistir a Royal Edinburgh Military Tattoo',
  'Vivir St Patrick''s Day',
  'Vivir Up Helly Aa',
  'Vivir King''s Day',
  'Asistir a Carnaval de Binche',
  'Vivir Fete de la Musique en Paris',
  'Vivir Festival of Lights',
  'Asistir a Festival de Avignon',
  'Vivir White Nights',
  'Asistir a Maslenitsa',
  'Vivir Midsummer',
  'Vivir Juhannus',
  'Asistir a Festival de Santa Lucia',
  'Vivir Constitution Day',
  'Vivir Song and Dance Festival',
  'Vivir Carnaval de Rijeka',
  'Asistir a Festival de Guca',
  'Vivir Kukeri',
  'Asistir a Festival de Sighisoara Medieval',
  'Vivir Busojaras',
  'Vivir Nevruz',
  'Asistir a Whirling Dervishes en contexto respetuoso',
  'Vivir Nowruz',
  'Vivir Vardavar',
  'Vivir Tbilisoba',
  'Asistir a Jerash Festival',
  'Vivir Ramadan y un iftar comunitario con respeto local',
  'Vivir Eid en comunidad invitada',
  'Vivir Moussem cultural tradicional',
  'Vivir Festival de Gnaoua',
  'Vivir Timkat',
  'Asistir a Festival au Desert o equivalente cuando sea seguro',
  'Vivir Durbar festival',
  'Vivir Homowo',
  'Vivir Ouidah Voodoo Festival',
  'Vivir Umhlanga Reed Dance con respeto y acceso permitido',
  'Vivir Cape Town Minstrel Carnival',
  'Vivir Carnaval de Rio',
  'Ver desfile de samba en Sambadromo',
  'Vivir Carnaval de Salvador',
  'Vivir Festa Junina',
  'Vivir Virgen de la Candelaria',
  'Vivir Carnaval de Oruro',
  'Vivir Fiesta de la Tirana',
  'Vivir Dia de Muertos',
  'Vivir Carnaval de Veracruz',
  'Vivir Semana Santa en Antigua',
  'Vivir Feria de las Flores',
  'Vivir Carnaval de Barranquilla',
  'Vivir Carnaval de Negros y Blancos',
  'Vivir Trinidad Carnival',
  'Vivir Albuquerque Balloon Fiesta desde su dimension cultural',
  'Vivir Powwow con acceso publico y respeto de protocolos',
  'Vivir Calgary Stampede como tradicion occidental',
  'Vivir Chinese New Year',
  'Vivir Mid-Autumn Festival',
  'Vivir Harbin Ice Festival',
  'Vivir Naadam',
  'Vivir Setsubun en un templo',
  'Vivir Hanami en temporada',
  'Vivir Chuseok en contexto cultural',
  'Vivir Boryeong Mud Festival',
  'Vivir Lantern Festival',
  'Vivir Thaipusam',
  'Vivir Loi Krathong',
  'Vivir Yi Peng',
  'Vivir Tet',
  'Vivir Hoi An Lantern Festival',
  'Vivir Galungan',
  'Vivir Bali Arts Festival',
  'Vivir Durga Puja',
  'Vivir Kumbh Mela en una edicion oficial',
  'Vivir Onam',
  'Vivir Esala Perahera',
  'Vivir Dashain',
  'Vivir Paro Tsechu',
  'Vivir Sydney New Year''s Eve desde perspectiva cultural',
  'Ver una opera en Teatro La Fenice',
  'Ver una opera en Wiener Staatsoper',
  'Ver una opera en Palais Garnier',
  'Ver una opera en Royal Opera House',
  'Ver una opera en Metropolitan Opera',
  'Ver una opera en Sydney Opera House',
  'Ver una representacion de Shakespeare en Globe Theatre',
  'Ver un musical en West End',
  'Ver un musical en Broadway',
  'Ver ballet en Bolshoi Theatre',
  'Ver ballet en Mariinsky Theatre',
  'Ver ballet en Opera de Paris',
  'Ver flamenco en un tablao de referencia',
  'Ver una zambra en Sacromonte',
  'Ver fado en una casa tradicional',
  'Ver cante alentejano',
  'Ver rebetiko en vivo',
  'Ver danza derviche sema en contexto cultural',
  'Ver teatro kabuki',
  'Ver teatro noh',
  'Ver bunraku',
  'Ver sumo desde perspectiva cultural',
  'Ver pansori',
  'Ver una representacion de Beijing Opera',
  'Ver una funcion de water puppetry',
  'Ver danza Apsara',
  'Ver danza Khon',
  'Ver kecak en Uluwatu',
  'Ver danza barong',
  'Ver gamelan en vivo',
  'Ver kathakali',
  'Ver bharatanatyam',
  'Ver una performance de qawwali',
  'Ver una ceremonia de tambores taiko',
  'Ver haka en contexto maori respetuoso',
  'Ver una actuacion de didgeridoo por artistas aborigenes',
  'Asistir a Venice Biennale Arte',
  'Asistir a Documenta en una edicion vigente',
  'Asistir a Art Basel',
  'Asistir a Frieze London',
  'Asistir a ARCOmadrid',
  'Asistir a Paris Photo',
  'Asistir a Festival de Cannes',
  'Asistir a Venice Film Festival',
  'Asistir a Berlinale',
  'Asistir a San Sebastian Film Festival',
  'Asistir a Sundance Film Festival',
  'Asistir a Toronto International Film Festival',
  'Asistir a Busan International Film Festival',
  'Visitar Shakespeare and Company y comprar un libro',
  'Visitar la casa de Shakespeare',
  'Seguir los escenarios literarios de James Joyce',
  'Visitar Jane Austen Centre',
  'Visitar Museo Casa de Cervantes',
  'Seguir la Barcelona literaria de Carlos Ruiz Zafon',
  'Visitar Casa Museo de Federico Garcia Lorca',
  'Visitar Casa di Dante',
  'Seguir la Praga de Kafka',
  'Visitar Goethe House',
  'Visitar Tolstoy Museum Estate Yasnaya Polyana',
  'Visitar Anne Frank House',
  'Visitar Hemingway Home',
  'Visitar Mark Twain House',
  'Visitar Pablo Neruda''s La Chascona',
  'Visitar Casa Azul de Frida Kahlo desde contexto biografico',
  'Visitar Museo Casa de Gabriel Garcia Marquez o ruta asociada',
  'Visitar Borges cultural sites',
  'Visitar Ghibli Museum',
  'Visitar Ghibli Park',
  'Visitar Toei Animation Museum',
  'Visitar Kyoto International Manga Museum',
  'Visitar Akihabara entendiendo su cultura otaku',
  'Visitar Seoul webtoon/culture spaces',
  'Visitar Hollywood Academy Museum',
  'Hacer un tour de estudios de cine',
  'Visitar Cinecitta Studios',
  'Visitar Hobbiton como patrimonio cinematografico contemporaneo'
  )
  and not exists (select 1 from user_gooals u where u.gooal_id = g.id);

-- ── musica (53 títulos buenos) ──
delete from gooals_v2 g
where g.categoria = 'musica'
  and g.titulo not in (
  'Ir a un concierto de tu grupo favorito',
  'Ir a un concierto en un estadio',
  'Ir a un festival de música de varios días',
  'Asistir a un concierto de música clásica',
  'Ir a la ópera',
  'Ver un musical en un teatro',
  'Ver un concierto de jazz en un club pequeño',
  'Ir a un concierto de un grupo que no conocías',
  'Ver tocar a una orquesta sinfónica en directo',
  'Ir a un concierto acústico o desenchufado',
  'Ver a un artista en su ciudad natal',
  'Ir a un concierto tú solo',
  'Viajar a otro país solo para ver un concierto',
  'Salir de fiesta hasta que amanezca',
  'Salir de fiesta en Ibiza',
  'Bailar en una sesión de música electrónica de más de seis horas',
  'Ir a una fiesta en la playa hasta el amanecer',
  'Ir a una rave',
  'Cantar en un karaoke delante de desconocidos',
  'Aprender a tocar un instrumento',
  'Tocar una canción entera delante de público',
  'Cantar delante de público',
  'Tocar en una banda o grupo',
  'Dar un concierto de pago',
  'Participar en una jam session',
  'Grabar una canción en un estudio',
  'Componer una canción propia',
  'Aprender a pinchar y hacer una sesión',
  'Cantar en un coro',
  'Tocar un instrumento en la calle',
  'Ver flamenco en un tablao',
  'Ver flamenco en Sevilla o Jerez',
  'Ver tango en directo en Buenos Aires',
  'Ver samba en directo en Río de Janeiro',
  'Ver fado en Lisboa',
  'Ver jazz en directo en Nueva Orleans',
  'Ver country en directo en Nashville',
  'Ver reggae en directo en Jamaica',
  'Ver música en directo en un pub de Dublín',
  'Ver blues en directo en un club de Chicago',
  'Ver ópera en Italia',
  'Ver un espectáculo de danza tradicional en Asia',
  'Escuchar tambores en directo en África occidental',
  'Ver una banda tocando en la calle y quedarte hasta el final',
  'Ir a una verbena o fiesta mayor de pueblo',
  'Ver una procesión de Semana Santa con banda',
  'Comprar un vinilo en una tienda de discos',
  'Ver a un artista dos veces en la misma gira',
  'Ver en directo a los cinco artistas que más escuchas',
  'Ver un concierto en cinco países distintos',
  'Ir a un festival en otro continente',
  'Conocer en persona a un músico que admiras',
  'Aprenderte una canción entera en otro idioma'
  )
  and not exists (select 1 from user_gooals u where u.gooal_id = g.id);

-- ── espectaculos (808 títulos buenos) ──
delete from gooals_v2 g
where g.categoria = 'espectaculos'
  and g.titulo not in (
  'Ver un partido en el Santiago Bernabéu',
  'Ver un partido en el Spotify Camp Nou',
  'Ver un partido en el Riyadh Air Metropolitano',
  'Ver un partido en el San Mamés',
  'Ver un partido en el Benito Villamarín',
  'Ver un partido en el Ramón Sánchez-Pizjuán',
  'Ver un partido en Mestalla',
  'Ver un partido en el Reale Arena',
  'Ver un partido en el Estadio de la Cerámica',
  'Ver un partido en el RCDE Stadium',
  'Ver un partido en Montilivi',
  'Ver un partido en El Sadar',
  'Ver un partido en Balaídos',
  'Ver un partido en Son Moix',
  'Ver un partido en Mendizorroza',
  'Ver un partido en el Coliseum',
  'Ver un partido en Vallecas',
  'Ver un partido en el Ciutat de València',
  'Ver un partido en el Martínez Valero',
  'Ver un partido en el Carlos Tartiere',
  'Ver un partido en el Emirates Stadium',
  'Ver un partido en Villa Park',
  'Ver un partido en el Vitality Stadium',
  'Ver un partido en el Gtech Community Stadium',
  'Ver un partido en el Amex Stadium',
  'Ver un partido en Stamford Bridge',
  'Ver un partido en Selhurst Park',
  'Ver un partido en el Hill Dickinson Stadium',
  'Ver un partido en Craven Cottage',
  'Ver un partido en Elland Road',
  'Ver un partido en Anfield',
  'Ver un partido en el Etihad Stadium',
  'Ver un partido en Old Trafford',
  'Ver un partido en St James'' Park',
  'Ver un partido en el City Ground',
  'Ver un partido en el Stadium of Light',
  'Ver un partido en el Tottenham Hotspur Stadium',
  'Ver un partido en el Coventry Building Society Arena',
  'Ver un partido en Portman Road',
  'Ver un partido en el MKM Stadium',
  'Ver un partido en el Allianz Arena',
  'Ver un partido en el Signal Iduna Park',
  'Ver un partido en el BayArena',
  'Ver un partido en el Deutsche Bank Park',
  'Ver un partido en el Red Bull Arena · Leipzig',
  'Ver un partido en el MHPArena',
  'Ver un partido en el BORUSSIA-PARK',
  'Ver un partido en el Europa-Park Stadion',
  'Ver un partido en el Volkswagen Arena',
  'Ver un partido en el Weserstadion',
  'Ver un partido en el MEWA Arena',
  'Ver un partido en el PreZero Arena',
  'Ver un partido en el Millerntor-Stadion',
  'Ver un partido en el Volksparkstadion',
  'Ver un partido en el RheinEnergieSTADION',
  'Ver un partido en el WWK Arena',
  'Ver un partido en el Alte Försterei',
  'Ver un partido en el Voith-Arena',
  'Ver un partido en San Siro',
  'Ver un partido en el Allianz Stadium · Turín',
  'Ver un partido en el Diego Armando Maradona',
  'Ver un partido en el Stadio Olimpico',
  'Ver un partido en el Gewiss Stadium',
  'Ver un partido en el Artemio Franchi',
  'Ver un partido en el Renato Dall''Ara',
  'Ver un partido en el Bluenergy Stadium',
  'Ver un partido en el Luigi Ferraris',
  'Ver un partido en el Olimpico Grande Torino',
  'Ver un partido en el Mapei Stadium',
  'Ver un partido en el Via del Mare',
  'Ver un partido en el Unipol Domus',
  'Ver un partido en el Ennio Tardini',
  'Ver un partido en el Giuseppe Sinigaglia',
  'Ver un partido en el Parc des Princes',
  'Ver un partido en el Orange Vélodrome',
  'Ver un partido en el Groupama Stadium',
  'Ver un partido en el Stade Pierre-Mauroy',
  'Ver un partido en Bollaert-Delelis',
  'Ver un partido en La Beaujoire',
  'Ver un partido en el Roazhon Park',
  'Ver un partido en el Stade Louis II',
  'Ver un partido en La Meinau',
  'Ver un partido en el Allianz Riviera',
  'Ver un partido en el Estádio da Luz',
  'Ver un partido en el José Alvalade',
  'Ver un partido en el Estádio do Dragão',
  'Ver un partido en el Municipal de Braga',
  'Ver un partido en el D. Afonso Henriques',
  'Ver un partido en el Johan Cruijff ArenA',
  'Ver un partido en De Kuip',
  'Ver un partido en el Philips Stadion',
  'Ver un partido en De Grolsch Veste',
  'Ver un partido en el AFAS Stadion',
  'Ver un partido en Celtic Park',
  'Ver un partido en Ibrox',
  'Ver un partido en Tynecastle Park',
  'Ver un partido en Easter Road',
  'Ver un partido en Pittodrie',
  'Ver un partido en el RAMS Park',
  'Ver un partido en el Tüpraş Stadyumu',
  'Ver un partido en el Şükrü Saracoğlu',
  'Ver un partido en el Más Monumental',
  'Ver un partido en La Bombonera',
  'Ver un partido en el Presidente Perón',
  'Ver un partido en el Libertadores de América',
  'Ver un partido en Pedro Bidegain',
  'Ver un partido en el José Amalfitani',
  'Ver un partido en el Jorge Luis Hirschi',
  'Ver un partido en el Maracaná',
  'Ver un partido en el Allianz Parque',
  'Ver un partido en el Neo Química Arena',
  'Ver un partido en el MorumBIS',
  'Ver un partido en Vila Belmiro',
  'Ver un partido en el Arena MRV',
  'Ver un partido en el Mineirão',
  'Ver un partido en el Arena do Grêmio',
  'Ver un partido en Beira-Rio',
  'Ver un partido en Fonte Nova',
  'Ver un partido en el BMO Stadium',
  'Ver un partido en el Dignity Health Sports Park',
  'Ver un partido en el Lumen Field',
  'Ver un partido en el Providence Park',
  'Ver un partido en el BC Place',
  'Ver un partido en el BMO Field',
  'Ver un partido en el Sports Illustrated Stadium',
  'Ver un partido en el Mercedes-Benz Stadium',
  'Ver un partido en el Chase Stadium',
  'Ver un partido en el Q2 Stadium',
  'Ver un partido en el Lower.com Field',
  'Ver un partido en el TQL Stadium',
  'Ver un partido en el Geodis Park',
  'Ver un partido en el Estadio Azteca',
  'Ver un partido en el Olímpico Universitario',
  'Ver un partido en el Estadio Akron',
  'Ver un partido en el Estadio BBVA',
  'Ver un partido en el Estadio Universitario',
  'Ver un partido en Nemesio Díez',
  'Ver un partido en el Saitama Stadium 2002',
  'Ver un partido en el Nissan Stadium',
  'Ver un partido en el Panasonic Stadium Suita',
  'Ver un partido en el Seoul World Cup Stadium',
  'Ver un partido en el Jeonju World Cup Stadium',
  'Ver un partido en el Kingdom Arena',
  'Ver un partido en el Al-Awwal Park',
  'Ver un partido en el King Abdullah Sports City',
  'Ver un partido en el Allianz Stadium · Sídney',
  'Ver un partido en el AAMI Park',
  'Ver un partido en el Jan Breydelstadion',
  'Ver un partido en el Lotto Park',
  'Ver un partido en Wankdorf',
  'Ver un partido en el St. Jakob-Park',
  'Ver un partido en el Red Bull Arena · Salzburgo',
  'Ver un partido en Parken',
  'Ver un partido en el Eleda Stadion',
  'Ver un partido en el Aspmyra Stadion',
  'Ver un partido en el Wojska Polskiego',
  'Ver un partido en el Fortuna Arena',
  'Ver un partido en el epet ARENA',
  'Ver un partido en Maksimir',
  'Ver un partido en el Rajko Mitić',
  'Ver un partido en el OPAP Arena',
  'Ver un partido en el Karaiskakis',
  'Ver un partido en Toumba',
  'Ver un partido en el Arena Națională',
  'Ver un partido en el Groupama Aréna',
  'Ver un partido en el Gran Parque Central',
  'Ver un partido en el Campeón del Siglo',
  'Ver un partido en el Monumental David Arellano',
  'Ver un partido en el Monumental U',
  'Ver un partido en el Alejandro Villanueva',
  'Ver un partido en el Rodrigo Paz Delgado',
  'Ver un partido en el Atanasio Girardot',
  'Ver un partido en el Metropolitano',
  'Ver un partido en el Hernando Siles',
  'Ver un partido en el Stade Mohammed V',
  'Ver un partido en el Cairo International Stadium',
  'Ver un partido en Loftus Versfeld',
  'Ir al Download Festival',
  'Ir al Reading Festival',
  'Ir al Leeds Festival',
  'Ir al Isle of Wight Festival',
  'Ir al TRNSMT',
  'Ir al 2000trees',
  'Ir al ArcTanGent',
  'Ir al Bloodstock Open Air',
  'Ir al Rebellion Punk Music Festival',
  'Ir al Slam Dunk Festival',
  'Ir al Rock am Ring',
  'Ir al Rock im Park',
  'Ir al Wacken Open Air',
  'Ir al Hurricane Festival',
  'Ir al Southside Festival',
  'Ir al Summer Breeze Open Air',
  'Ir al Full Force',
  'Ir al Rockharz Open Air',
  'Ir al Hellfest',
  'Ir al Main Square Festival',
  'Ir al Les Vieilles Charrues',
  'Ir al Rock en Seine',
  'Ir al Musilac',
  'Ir al Motocultor Festival',
  'Ir al Graspop Metal Meeting',
  'Ir al Rock Werchter',
  'Ir al Pukkelpop',
  'Ir al Alcatraz Open Air',
  'Ir al Pinkpop',
  'Ir al Jera On Air',
  'Ir al Dynamo Metalfest',
  'Ir al Paaspop',
  'Ir al Lowlands',
  'Ir al Roskilde Festival',
  'Ir al Copenhell',
  'Ir al NorthSide',
  'Ir al Sweden Rock Festival',
  'Ir al Way Out West',
  'Ir al Gefle Metal Festival',
  'Ir al Tuska Open Air',
  'Ir al Ruisrock',
  'Ir al Provinssi',
  'Ir al Ilosaarirock',
  'Ir al Tons of Rock',
  'Ir al Inferno Metal Festival',
  'Ir al Øya Festival',
  'Ir al Bergenfest',
  'Ir al Mystic Festival',
  'Ir al Pol''and''Rock Festival',
  'Ir al Open''er Festival',
  'Ir al Masters of Rock',
  'Ir al Rock for People',
  'Ir al Brutal Assault',
  'Ir al Nova Rock',
  'Ir al Frequency Festival',
  'Ir al Greenfield Festival',
  'Ir al Paléo Festival',
  'Ir al OpenAir St. Gallen',
  'Ir al Rock The Lakes',
  'Ir al Rockstadt Extreme Fest',
  'Ir al Electric Castle',
  'Ir al Sziget Festival',
  'Ir al FEZEN Festival',
  'Ir al Exit Festival',
  'Ir al Arsenal Fest',
  'Ir al INmusic Festival',
  'Ir al Rockstadt?',
  'Ir al Hills of Rock',
  'Ir al Midalidare Rock In The Wine Valley',
  'Ir al Ejekt Festival',
  'Ir al Release Athens',
  'Ir al Rockwave Festival',
  'Ir al Rock for People?',
  'Ir al Rock in Roma',
  'Ir al Firenze Rocks',
  'Ir al I-Days Milano',
  'Ir al Lucca Summer Festival',
  'Ir al Rock The Castle',
  'Ir al Resurrection Fest',
  'Ir al Mad Cool Festival',
  'Ir al Azkena Rock Festival',
  'Ir al Barcelona Rock Fest',
  'Ir al Leyendas del Rock',
  'Ir al Viña Rock',
  'Ir al CanelaParty',
  'Ir al Primavera Sound',
  'Ir al NOS Alive',
  'Ir al MEO Kalorama',
  'Ir al Vilar de Mouros',
  'Ir al SonicBlast Fest',
  'Ir al Hell of a Weekend',
  'Ir al Rockwave?',
  'Ir al Sick New World',
  'Ir al Welcome to Rockville',
  'Ir al Sonic Temple Art & Music Festival',
  'Ir al Aftershock Festival',
  'Ir al Louder Than Life',
  'Ir al Rocklahoma',
  'Ir al Inkcarceration',
  'Ir al Maryland Deathfest',
  'Ir al Milwaukee Metal Fest',
  'Ir al Punk Rock Bowling',
  'Ir al Riot Fest',
  'Ir al Shaky Knees',
  'Ir al When We Were Young',
  'Ir al Vans Warped Tour',
  'Ir al BottleRock Napa Valley',
  'Ir al Austin City Limits Music Festival',
  'Ir al Lollapalooza Chicago',
  'Ir al Bonnaroo',
  'Ir al Boston Calling',
  'Ir al Sea.Hear.Now',
  'Ir al Osheaga',
  'Ir al FEQ - Festival d''été de Québec',
  'Ir al Heavy Montréal / related metal events',
  'Ir al Rifflandia',
  'Ir al Rock in Rio',
  'Ir al The Town',
  'Ir al Lollapalooza Brasil',
  'Ir al Porão do Rock',
  'Ir al Knotfest Brasil',
  'Ir al Cosquín Rock',
  'Ir al Quilmes Rock',
  'Ir al Lollapalooza Argentina',
  'Ir al Rock al Parque',
  'Ir al Estéreo Picnic',
  'Ir al Vive Latino',
  'Ir al Corona Capital',
  'Ir al Tecate Pa''l Norte',
  'Ir al Knotfest México',
  'Ir al Hell & Heaven Metal Fest',
  'Ir al Lollapalooza Chile',
  'Ir al Fauna Primavera',
  'Ir al Rockódromo',
  'Ir al Good Things Festival',
  'Ir al Download Festival Australia*',
  'Ir al Yours & Owls',
  'Ir al Splendour in the Grass*',
  'Ir al Laneway Festival',
  'Ir al Bluesfest Byron Bay',
  'Ir al Homegrown',
  'Ir al Fuji Rock Festival',
  'Ir al Summer Sonic Tokyo',
  'Ir al Summer Sonic Osaka',
  'Ir al Loud Park',
  'Ir al Rock in Japan Festival',
  'Ir al Pentaport Rock Festival',
  'Ir al Busan International Rock Festival',
  'Ir al Clockenflap',
  'Ir al Baybeats',
  'Ir al Hammersonic Festival',
  'Ir al Java Rockin''land*',
  'Ir al Oppikoppi*',
  'Ir al Ramfest',
  'Ir al Up The Creek',
  'Ir al Tomorrowland',
  'Ir al Tomorrowland Winter',
  'Ir al Creamfields',
  'Ir al Parklife',
  'Ir al Field Day',
  'Ir al Junction 2',
  'Ir al Emerge Festival',
  'Ir al Lost Village',
  'Ir al Houghton Festival',
  'Ir al Boomtown Fair',
  'Ir al Love Saves The Day',
  'Ir al Terminal V Festival',
  'Ir al Time Warp',
  'Ir al MELT Festival*',
  'Ir al Nation of Gondwana',
  'Ir al Fusion Festival',
  'Ir al Airbeat One',
  'Ir al Parookaville',
  'Ir al Nature One',
  'Ir al Mayday',
  'Ir al Sea You Festival',
  'Ir al Sónar Barcelona',
  'Ir al Monegros Desert Festival',
  'Ir al Medusa Festival',
  'Ir al Dreambeach',
  'Ir al Aquasella',
  'Ir al A Summer Story',
  'Ir al Brunch Electronik Festival',
  'Ir al OFFSónar',
  'Ir al DGTL Barcelona',
  'Ir al Sun & Snow Weekend',
  'Ir al Neopop Festival',
  'Ir al Boom Festival',
  'Ir al Lisboa Electronica',
  'Ir al RFM Somnii',
  'Ir al Ultra Europe',
  'Ir al Sonus Festival',
  'Ir al Hideout Festival',
  'Ir al Defected Croatia',
  'Ir al Dimensions Festival',
  'Ir al Love International',
  'Ir al Hospitality On The Beach',
  'Ir al UNUM Festival',
  'Ir al Kala Festival',
  'Ir al ION Festival',
  'Ir al Untold Festival',
  'Ir al Neversea',
  'Ir al Balaton Sound*',
  'Ir al B.my.Lake*',
  'Ir al Lovefest',
  'Ir al Sea Dance*',
  'Ir al Awakenings Festival',
  'Ir al DGTL Amsterdam',
  'Ir al Mysteryland',
  'Ir al Defqon.1',
  'Ir al Decibel Outdoor',
  'Ir al Dominator Festival',
  'Ir al Verknipt Festival',
  'Ir al Free Your Mind Festival',
  'Ir al Loveland Festival',
  'Ir al Dekmantel',
  'Ir al Amsterdam Dance Event (ADE)',
  'Ir al A State of Trance Festival',
  'Ir al Luminosity Beach Festival',
  'Ir al Liquicity Festival',
  'Ir al Draaimolen Festival',
  'Ir al Extrema Outdoor Belgium',
  'Ir al Rampage Open Air',
  'Ir al Dour Festival',
  'Ir al Les Ardentes',
  'Ir al Kappa FuturFestival',
  'Ir al Nameless Festival',
  'Ir al Decibel Open Air',
  'Ir al Movement Torino',
  'Ir al Polifonic Festival',
  'Ir al Sonar Lisboa*',
  'Ir al Les Plages Électroniques',
  'Ir al Nuits Sonores',
  'Ir al Peacock Society',
  'Ir al Elektric Park',
  'Ir al Delta Festival',
  'Ir al Astropolis',
  'Ir al Garorock',
  'Ir al Street Parade',
  'Ir al SunIce Festival',
  'Ir al Caprices Festival',
  'Ir al Terrazzza - Horse Park Festival',
  'Ir al Electric Love Festival',
  'Ir al Shutdown Festival',
  'Ir al Lake Festival*',
  'Ir al Electric Nation',
  'Ir al Audioriver',
  'Ir al Instytut Festival',
  'Ir al Fest Festival*',
  'Ir al Beats for Love',
  'Ir al Let It Roll',
  'Ir al Máchá■ Festival',
  'Ir al Pohoda Festival',
  'Ir al Grape Festival',
  'Ir al Dimensions?',
  'Ir al Flow Festival',
  'Ir al Weekend Festival',
  'Ir al Summer Sound',
  'Ir al Findings Festival*',
  'Ir al Stavernfestivalen',
  'Ir al Distortion',
  'Ir al Karrusel',
  'Ir al Department Festival',
  'Ir al Into the Valley*',
  'Ir al Iceland Airwaves',
  'Ir al Secret Solstice*',
  'Ir al Insomnia Festival',
  'Ir al Semibreve',
  'Ir al Waking Life',
  'Ir al Ultra Music Festival',
  'Ir al EDC Las Vegas',
  'Ir al EDC Orlando',
  'Ir al Electric Forest',
  'Ir al Movement Detroit',
  'Ir al Beyond Wonderland SoCal',
  'Ir al Nocturnal Wonderland',
  'Ir al Escape Halloween',
  'Ir al Countdown NYE',
  'Ir al Hard Summer',
  'Ir al CRSSD Festival',
  'Ir al Portola Music Festival',
  'Ir al Lightning in a Bottle',
  'Ir al Coachella',
  'Ir al Desert Hearts Festival',
  'Ir al ARC Music Festival',
  'Ir al North Coast Music Festival',
  'Ir al Electric Zoo*',
  'Ir al Governors Ball',
  'Ir al Elements Music & Arts Festival',
  'Ir al Lost Lands',
  'Ir al Secret Dreams',
  'Ir al Okeechobee Music & Arts Festival',
  'Ir al III Points',
  'Ir al Seismic Dance Event',
  'Ir al Freaky Deaky',
  'Ir al Ubbi Dubbi',
  'Ir al Lights All Night',
  'Ir al Das Energi',
  'Ir al Bass Canyon',
  'Ir al Beyond Wonderland at The Gorge',
  'Ir al Shambhala Music Festival',
  'Ir al ÎLESONIQ',
  'Ir al VELD Music Festival',
  'Ir al Escapade Music Festival',
  'Ir al Igloofest',
  'Ir al Bass Coast',
  'Ir al Chasing Summer',
  'Ir al EDC México',
  'Ir al Dreamfields México',
  'Ir al Zamna Festival',
  'Ir al BPM Festival Costa Rica',
  'Ir al Resistance Buenos Aires',
  'Ir al Creamfields Argentina',
  'Ir al Ultra Buenos Aires',
  'Ir al Ultra Brasil',
  'Ir al Tomorrowland Brasil',
  'Ir al Só Track Boa',
  'Ir al XXXperience Festival',
  'Ir al Universo Paralello',
  'Ir al Resistance Santiago',
  'Ir al Creamfields Chile',
  'Ir al Baum Festival',
  'Ir al Ritvales',
  'Ir al Road to Ultra Peru',
  'Ir al Ultra Japan',
  'Ir al Rainbow Disco Club',
  'Ir al Summer Sonic',
  'Ir al ZoukOut',
  'Ir al S2O Songkran Music Festival',
  'Ir al 808 Festival',
  'Ir al Wonderfruit',
  'Ir al Djakarta Warehouse Project',
  'Ir al We The Fest',
  'Ir al Ultra Korea',
  'Ir al World DJ Festival',
  'Ir al Creamfields Hong Kong',
  'Ir al Ultra Taiwan',
  'Ir al S2O Taiwan',
  'Ir al EDC China',
  'Ir al Sunburn Festival',
  'Ir al VH1 Supersonic',
  'Ir al Magnetic Fields Festival',
  'Ir al MDLBEAST Soundstorm',
  'Ir al Balad Beast',
  'Ir al Untold Dubai',
  'Ir al Groove on the Grass',
  'Ir al Pitch Music & Arts',
  'Ir al Beyond The Valley',
  'Ir al Wildlands',
  'Ir al Festival X*',
  'Ir al Listen Out',
  'Ir al Subsonic Music Festival',
  'Ir al Strawberry Fields',
  'Ir al Rabbits Eat Lettuce',
  'Ir al Electric Gardens',
  'Ir al Snow Machine',
  'Ir al Rhythm and Vines',
  'Ir al Northern Bass',
  'Ir al AfrikaBurn',
  'Ir al Ultra South Africa',
  'Ir al Rocking the Daisies',
  'Ir al Bazique',
  'Ir al Oasis Festival',
  'Ir al MOGA Essaouira',
  'Ir al Sandbox Festival',
  'Vivir el Carnaval de Río',
  'Vivir San Fermín',
  'Vivir el Día del Rey',
  'Vivir el Oktoberfest',
  'Vivir Holi',
  'Vivir Songkran',
  'Vivir el Día de Muertos',
  'Vivir Mardi Gras',
  'Vivir el Carnaval de Venecia',
  'Vivir las Fallas',
  'Vivir la Tomatina',
  'Vivir el día de San Patricio',
  'Vivir el Yi Peng',
  'Vivir Inti Raymi',
  'Vivir el Carnaval de Barranquilla',
  'Vivir el Carnaval de Oruro',
  'Vivir el Año Nuevo Chino',
  'Vivir el Año Nuevo Chino · Singapur',
  'Vivir Gion Matsuri',
  'Vivir el festival de globos de Albuquerque',
  'Vivir la Feria de Abril',
  'Vivir el Carnaval de Santa Cruz de Tenerife',
  'Vivir la Patum',
  'Vivir Moros y Cristianos',
  'Vivir el Carnaval de Cádiz',
  'Vivir la Romería del Rocío',
  'Vivir la Batalla del Vino',
  'Vivir Cascamorras',
  'Vivir el Palio di Siena',
  'Vivir la Batalla de las Naranjas',
  'Vivir Infiorata di Noto',
  'Vivir el Carnaval de Colonia',
  'Vivir la Krampusnacht',
  'Vivir Fête des Lumières',
  'Vivir Bastille Day',
  'Vivir el Carnaval de Niza',
  'Vivir el carnaval de Notting Hill',
  'Vivir el Up Helly Aa',
  'Vivir el Hogmanay de Edimburgo',
  'Vivir el carnaval de Basilea',
  'Vivir el Carnaval de Binche',
  'Vivir Festa de São João',
  'Vivir Festa de Santo António',
  'Vivir Pushkar Camel Fair',
  'Vivir Diwali',
  'Vivir Kumbh Mela',
  'Vivir el Thaipusam',
  'Vivir Loy Krathong',
  'Vivir el festival del barro de Boryeong',
  'Vivir Sapporo Snow Festival',
  'Vivir el Hanami',
  'Vivir Awa Odori',
  'Vivir Nebuta Matsuri',
  'Vivir Hadaka Matsuri',
  'Vivir Sinulog',
  'Vivir Ati-Atihan',
  'Vivir Nyepi',
  'Vivir Galungan y Kuningan',
  'Vivir el Naadam',
  'Vivir Harbin Ice and Snow Festival',
  'Vivir Dragon Boat Festival',
  'Vivir Pingxi Sky Lantern Festival',
  'Vivir la Fiesta de la Vendimia',
  'Vivir el Carnaval de Gualeguaychú',
  'Vivir el Carnaval de Salvador',
  'Vivir Festa Junina / São João',
  'Vivir Círio de Nazaré',
  'Vivir el Festival de Parintins',
  'Vivir Carnival of Trinidad and Tobago',
  'Vivir Junkanoo',
  'Vivir Crop Over',
  'Vivir la Semana Santa de Antigua',
  'Vivir Guelaguetza',
  'Vivir la Noche de Rábanos',
  'Vivir la Fiesta de la Candelaria',
  'Vivir la Feria de las Flores',
  'Vivir el Festival de Negros y Blancos',
  'Vivir Burning Man',
  'Vivir Fantasy Fest',
  'Vivir Calgary Stampede',
  'Vivir Quebec Winter Carnival',
  'Vivir Celebration of Light',
  'Vivir Sydney New Year''s Eve',
  'Vivir Vivid Sydney',
  'Vivir Melbourne Cup Carnival',
  'Vivir Pasifika Festival',
  'Vivir Matariki',
  'Vivir el Timkat',
  'Vivir Meskel',
  'Vivir el Moussem de Tan-Tan',
  'Vivir el Festival de las Máscaras de Dédougou',
  'Vivir el Durbar',
  'Vivir el Lake of Stars',
  'Ver un partido en Wembley',
  'Ver un partido de la NBA en el Madison Square Garden',
  'Ver un partido de la NBA en el TD Garden',
  'Ver un partido de la NBA en el Crypto.com Arena',
  'Ver un partido de la NBA en el United Center',
  'Ver un partido de la Euroliga en el Movistar Arena',
  'Ver un partido de la Euroliga en el Palau Blaugrana',
  'Ver un partido de la NBA en el State Farm Arena',
  'Ver un partido de la NBA en el Barclays Center',
  'Ver un partido de la NBA en el Spectrum Center',
  'Ver un partido de la NBA en el Rocket Arena',
  'Ver un partido de la NBA en el American Airlines Center',
  'Ver un partido de la NBA en el Ball Arena',
  'Ver un partido de la NBA en el Little Caesars Arena',
  'Ver un partido de la NBA en el Chase Center',
  'Ver un partido de la NBA en el Toyota Center',
  'Ver un partido de la NBA en el Gainbridge Fieldhouse',
  'Ver un partido de la NBA en el Intuit Dome',
  'Ver un partido de la NBA en el FedExForum',
  'Ver un partido de la NBA en el Kaseya Center',
  'Ver un partido de la NBA en el Fiserv Forum',
  'Ver un partido de la NBA en el Target Center',
  'Ver un partido de la NBA en el Smoothie King Center',
  'Ver un partido de la NBA en el Paycom Center',
  'Ver un partido de la NBA en el Kia Center',
  'Ver un partido de la NBA en el Xfinity Mobile Arena',
  'Ver un partido de la NBA en el Mortgage Matchup Center',
  'Ver un partido de la NBA en el Moda Center',
  'Ver un partido de la NBA en el Golden 1 Center',
  'Ver un partido de la NBA en el Frost Bank Center',
  'Ver un partido de la NBA en el Scotiabank Arena',
  'Ver un partido de la NBA en el Delta Center',
  'Ver un partido de la NBA en el Capital One Arena',
  'Ver un partido de la Euroliga en el Buesa Arena',
  'Ver un partido de la Euroliga en el Roig Arena',
  'Ver un partido de la Euroliga en el Uber Arena',
  'Ver un partido de la Euroliga en el SAP Garden',
  'Ver un partido de la Euroliga en la Salle Gaston Médecin',
  'Ver un partido de la Euroliga en el LDLC Arena',
  'Ver un partido de la Euroliga en el Unipol Arena',
  'Ver un partido de la Euroliga en el Mediolanum Forum',
  'Ver un partido de la Euroliga en el OAKA',
  'Ver un partido de la Euroliga en el Estadio de la Paz y la Amistad',
  'Ver un partido de la Euroliga en el Ülker Sports and Event Hall',
  'Ver un partido de la Euroliga en el Basketball Development Center',
  'Ver un partido de la Euroliga en el Žalgirio Arena',
  'Ver un partido de la Euroliga en el Belgrade Arena',
  'Ver un partido de la Euroliga en el Menora Mivtachim Arena',
  'Ver un partido de la Euroliga en el Pais Arena',
  'Ver un Gran Premio de Fórmula 1 en Mónaco',
  'Ver las 24 Horas de Le Mans',
  'Ver un Gran Premio de Fórmula 1 en Monza',
  'Ver un Gran Premio de Fórmula 1 en Spa-Francorchamps',
  'Ver un Gran Premio de Fórmula 1 en Silverstone',
  'Ver un Gran Premio de Fórmula 1 en Suzuka',
  'Ver un Gran Premio de Fórmula 1 en Interlagos',
  'Ver un Gran Premio de Fórmula 1 en Montmeló',
  'Ver un Gran Premio de Fórmula 1 en el MADRING',
  'Ver un Gran Premio de Fórmula 1 en el Red Bull Ring',
  'Ver un Gran Premio de Fórmula 1 en el Hungaroring',
  'Ver un Gran Premio de Fórmula 1 en Zandvoort',
  'Ver un Gran Premio de Fórmula 1 en Melbourne',
  'Ver un Gran Premio de Fórmula 1 en Shanghái',
  'Ver un Gran Premio de Fórmula 1 en Miami',
  'Ver un Gran Premio de Fórmula 1 en Montreal',
  'Ver un Gran Premio de Fórmula 1 en el Circuit of The Americas',
  'Ver un Gran Premio de Fórmula 1 en Las Vegas',
  'Ver un Gran Premio de Fórmula 1 en Bakú',
  'Ver un Gran Premio de Fórmula 1 en Singapur',
  'Ver un Gran Premio de Fórmula 1 en Sepang',
  'Ver un Gran Premio de Fórmula 1 en el Hermanos Rodríguez',
  'Ver un Gran Premio de Fórmula 1 en Lusail',
  'Ver un Gran Premio de Fórmula 1 en Yas Marina',
  'Ver un Gran Premio de MotoGP en Assen',
  'Ver un Gran Premio de MotoGP en Mugello',
  'Ver un Gran Premio de MotoGP en Jerez',
  'Ver un Gran Premio de MotoGP en Montmeló',
  'Ver un Gran Premio de MotoGP en MotorLand Aragón',
  'Ver un Gran Premio de MotoGP en Cheste',
  'Ver un Gran Premio de MotoGP en Le Mans',
  'Ver un Gran Premio de MotoGP en Misano',
  'Ver un Gran Premio de MotoGP en Silverstone',
  'Ver un Gran Premio de MotoGP en el Sachsenring',
  'Ver un Gran Premio de MotoGP en el Red Bull Ring',
  'Ver un Gran Premio de MotoGP en Brno',
  'Ver un Gran Premio de MotoGP en Balaton Park',
  'Ver un Gran Premio de MotoGP en Portimão',
  'Ver un Gran Premio de MotoGP en el Circuit of The Americas',
  'Ver un Gran Premio de MotoGP en Goiânia',
  'Ver un Gran Premio de MotoGP en Motegi',
  'Ver un Gran Premio de MotoGP en Sepang',
  'Ver un Gran Premio de MotoGP en Buriram',
  'Ver un Gran Premio de MotoGP en Mandalika',
  'Ver un Gran Premio de MotoGP en Lusail',
  'Ver un Gran Premio de MotoGP en Phillip Island',
  'Ver un partido en Wimbledon',
  'Ver un partido en Roland Garros',
  'Ver un partido en el US Open',
  'Ver un partido en el Open de Australia',
  'Ver un partido en el Mutua Madrid Open',
  'Ver un partido en el Conde de Godó',
  'Ver un partido en Indian Wells',
  'Ver un partido en el Masters de Montecarlo',
  'Ver un partido en las ATP Finals',
  'Ver el Tour de Francia en Alpe d''Huez',
  'Ver el Tour de Francia en el Mont Ventoux',
  'Ver la Vuelta a España en el Angliru',
  'Ver un concierto en el Red Rocks Amphitheatre',
  'Ver un concierto en el Hollywood Bowl',
  'Ver un concierto en el Royal Albert Hall',
  'Ver una ópera en La Scala',
  'Ver un concierto en la Ópera de Sídney',
  'Ver una ópera en el Metropolitan Opera House',
  'Ver una ópera en la Wiener Staatsoper',
  'Ver un concierto en el Musikverein',
  'Ver jazz en el Village Vanguard',
  'Ver jazz en el Blue Note de Tokio',
  'Ver jazz en el Preservation Hall',
  'Salir de fiesta en el Berghain',
  'Ver un concierto en el Cavern Club',
  'Ver un concierto en el Palau de la Música Catalana',
  'Ver un concierto en la Berliner Philharmonie',
  'Ver una ópera en el Palais Garnier',
  'Ver una ópera en La Fenice',
  'Ver un concierto en el Concertgebouw',
  'Ver una ópera en el Teatro Colón',
  'Ver un concierto en el Grand Ole Opry',
  'Ver un concierto en el Ryman Auditorium',
  'Ver un concierto en el Whisky a Go Go',
  'Ver un concierto en el Troubadour',
  'Ver fado en el Clube de Fado',
  'Visitar los estudios de Abbey Road',
  'Ver una carrera de la NASCAR en Daytona',
  'Ver una carrera de la NASCAR en Indianápolis',
  'Ver una carrera de la NASCAR en Talladega',
  'Ver una carrera de la NASCAR en Bristol',
  'Ver una carrera de la NASCAR en Darlington',
  'Ver una carrera de la NASCAR en Martinsville',
  'Ver una carrera de la NASCAR en Charlotte',
  'Ver una carrera de la NASCAR en North Wilkesboro',
  'Ver una carrera de la NASCAR en Phoenix',
  'Ver una carrera de la NASCAR en Las Vegas',
  'Ver una carrera de la NASCAR en Sonoma',
  'Ver una carrera de la NASCAR en Watkins Glen',
  'Ver una carrera de la NASCAR en el Circuit of The Americas',
  'Ver una carrera de la NASCAR en Atlanta',
  'Ver una carrera de la NASCAR en Kansas',
  'Ver una carrera de la NASCAR en Texas',
  'Ver una carrera de la NASCAR en Dover',
  'Ver una carrera de la NASCAR en Nashville',
  'Ver una carrera de la NASCAR en Michigan',
  'Ver una carrera de la NASCAR en Homestead-Miami',
  'Ver una carrera de la NASCAR en Richmond',
  'Ver una carrera de la NASCAR en Iowa',
  'Ver una carrera de la NASCAR en Rockingham',
  'Ver una carrera de la NASCAR en New Hampshire',
  'Ver una carrera de la NASCAR en Chicagoland',
  'Ver una carrera de la NASCAR en Bowman Gray',
  'Ver una carrera de la NASCAR en Lime Rock Park',
  'Ver una carrera de la NASCAR en St. Petersburg',
  'Ver una carrera de la NASCAR en Coronado',
  'Ver una carrera de la NASCAR en el World Wide Technology Raceway',
  'Ver una carrera de la NASCAR en el Lucas Oil Indianapolis Raceway Park',
  'Asistir a la final de un Mundial de fútbol',
  'Asistir a unos Juegos Olímpicos',
  'Asistir a una final de la Champions League',
  'Asistir a un partido de un Mundial de fútbol',
  'Asistir a la Super Bowl',
  'Asistir a una final de la NBA',
  'Asistir a un partido de una Eurocopa',
  'Asistir a una pelea de UFC',
  'Asistir a un combate de boxeo por un título mundial',
  'Asistir a una Ryder Cup'
  )
  and not exists (select 1 from user_gooals u where u.gooal_id = g.id);


-- ── Comprobación ───────────────────────────────────────────
-- deporte 605 · aventura 225 · cultura 437 · música 53 · espectáculos 715.
-- Espectáculos sube a 808 y el resto se completa con insertar.mjs después.
select categoria, count(*) as gooals
from gooals_v2 group by categoria order by 2 desc;
