-- ═══════════════════════════════════════════════════════════
-- GooALS — poner Supabase al día con el catálogo limpio
--
-- Supabase tiene 4.789 gooals y el catálogo nuevo tiene 4.726, pero no es un
-- ajuste de 63: han cambiado 797 filas por un lado y entran 734 por otro.
--
-- Lo que se retira:
--
--   música       503   el PDF entero. Eran nombres de festivales ("Vivir
--                      Bahidora") y pabellones intercambiables ("Ver un
--                      concierto en Hallenstadion"). Lo que valía se ha
--                      movido a Espectáculos, no se ha perdido.
--   deporte      235   títulos que quedaron partidos al quitarles el número,
--                      micro-técnica ("Aprender a frenar en T"), deportes que
--                      no conoce nadie, y los 86 de entrada reescritos
--                      ("Jugar un partido de baloncesto 5x5" → "Jugar al
--                      baloncesto").
--   aventura      28   los que llevaban "con guía" pegado y ahora se llaman
--                      igual pero sin la condición.
--   cultura       25   las fiestas que estaban duplicadas con Espectáculos
--                      (las Fallas, la Semana Santa...). Dos cobros por lo
--                      mismo.
--   gastronomía    2
--   espectáculos   4
--
-- Y después entran 734 nuevas: 365 festivales, 93 fiestas, 106 deportes de
-- entrada, 46 benchmarks de fuerza, 53 de música y las salas.
--
-- ── Los dos avisos de Supabase ─────────────────────────────────────
--
-- "destructive operations": sí, hay un DELETE. Es el objetivo.
-- "table without RLS": la tabla temporal de abajo solo existe en esta pestaña
-- del editor y desaparece al cerrarla. Falso positivo. Run without RLS.
--
-- El DELETE no puede llevarse nada de nadie: salta cualquier gooal que alguien
-- tenga en su lista.
-- ═══════════════════════════════════════════════════════════

create temp table a_borrar (categoria text, titulo text);
insert into a_borrar (categoria, titulo) values
  ('deporte', 'Aprender una rueda lateral'),
  ('deporte', 'Hacer flexiones seguidas'),
  ('deporte', 'Hacer una voltereta hacia delante controlada'),
  ('deporte', 'Aprender una rondada'),
  ('deporte', 'Completar 30 días de movilidad de 15 minutos'),
  ('deporte', 'Hacer tu primera pistol squat asistida'),
  ('deporte', 'Hacer tu primera bandera humana asistida'),
  ('deporte', 'Hacer 10 minutos diarios de movilidad durante 100 días'),
  ('deporte', 'Hacer un backflip en gimnasio con entrenador'),
  ('deporte', 'Hacer una clase de spinning de 90 minutos'),
  ('deporte', 'Aprender a cambiar una cámara en ruta'),
  ('deporte', 'Aprender un bunny hop en bicicleta'),
  ('deporte', 'Probar una bicicleta de pista'),
  ('deporte', 'Hacer un wheelie controlado de 20 metros'),
  ('deporte', 'Probar descenso MTB en bike park'),
  ('deporte', 'Entrenar días por semana durante semanas'),
  ('deporte', 'Hacer movilidad 10 minutos diarios durante un mes'),
  ('deporte', 'Aprender shuffle dance básico'),
  ('deporte', 'Aprender una secuencia básica de salsa'),
  ('deporte', 'Hacer una clase de bachata'),
  ('deporte', 'Hacer una clase de ballet para adultos'),
  ('deporte', 'Hacer una clase de danza africana'),
  ('deporte', 'Hacer una clase de danza contemporánea'),
  ('deporte', 'Hacer una clase de flamenco'),
  ('deporte', 'Hacer una clase de hip hop'),
  ('deporte', 'Hacer una clase de salsa'),
  ('deporte', 'Hacer una clase de zumba'),
  ('deporte', 'Aprender moonwalk'),
  ('deporte', 'Aprender una coreografía de 3 minutos'),
  ('deporte', 'Aprender una coreografía de bachata de 2 minutos'),
  ('deporte', 'Aprender una coreografía de hip hop completa'),
  ('deporte', 'Aprender una pequeña coreografía de flamenco'),
  ('deporte', 'Hacer una clase de breakdance'),
  ('deporte', 'Aprender un freeze básico de breakdance'),
  ('deporte', 'Aprender un giro doble controlado'),
  ('deporte', 'Aprender un six-step de breakdance'),
  ('deporte', 'Jugar un entrenamiento de cricket'),
  ('deporte', 'Jugar un partido de ultimate frisbee'),
  ('deporte', 'Jugar una partida de teqball'),
  ('deporte', 'Probar bochas'),
  ('deporte', 'Probar croquet'),
  ('deporte', 'Probar dragon boat'),
  ('deporte', 'Probar floorball'),
  ('deporte', 'Probar footgolf'),
  ('deporte', 'Probar fútbol playa'),
  ('deporte', 'Probar kin-ball'),
  ('deporte', 'Probar korfball'),
  ('deporte', 'Probar sumo recreativo con equipamiento inflable'),
  ('deporte', 'Probar ultimate frisbee'),
  ('deporte', 'Batear una bola en cricket'),
  ('deporte', 'Completar 18 hoyos de footgolf'),
  ('deporte', 'Jugar un partido de fútbol playa'),
  ('deporte', 'Probar SUP polo'),
  ('deporte', 'Probar futvóley'),
  ('deporte', 'Probar fútbol gaélico'),
  ('deporte', 'Probar hurling en una sesión de iniciación'),
  ('deporte', 'Probar kabaddi en sesión recreativa'),
  ('deporte', 'Probar lacrosse'),
  ('deporte', 'Probar pelota vasca'),
  ('deporte', 'Probar sepak takraw'),
  ('deporte', 'Mantener 10 intercambios en futvóley'),
  ('deporte', 'Probar jai alai con instructor'),
  ('deporte', 'Lanzar un caber de entrenamiento con instructor'),
  ('deporte', 'Aprender un salto agrupado en trampolín'),
  ('deporte', 'Hacer una clase de aro aéreo'),
  ('deporte', 'Hacer una clase de telas aéreas'),
  ('deporte', 'Probar acrobacia aérea en colchoneta con entrenador'),
  ('deporte', 'Probar trapecio volante con instructor'),
  ('deporte', 'Probar vuelo indoor en túnel de viento'),
  ('deporte', 'Aprender un front flip en trampolín con entrenador'),
  ('deporte', 'Hacer una figura invertida básica en telas aéreas'),
  ('deporte', 'Hacer una segunda sesión de vuelo indoor y controlar giros básicos'),
  ('deporte', 'Mantener una figura básica en aro aéreo 20 segundos'),
  ('deporte', 'Aprender un backflip en trampolín con entrenador'),
  ('deporte', 'Conducir una moto de agua en zona autorizada'),
  ('deporte', 'Probar esquí acuático'),
  ('deporte', 'Probar surf por primera vez'),
  ('deporte', 'Probar vela ligera'),
  ('deporte', 'Probar wakeboard'),
  ('deporte', 'Probar wakesurf'),
  ('deporte', 'Probar windsurf'),
  ('deporte', 'Gobernar un velero durante una hora con instructor'),
  ('deporte', 'Hacer body drag en kitesurf'),
  ('deporte', 'Hacer una ruta guiada en moto de agua'),
  ('deporte', 'Probar e-foil con instructor'),
  ('deporte', 'Probar kitesurf con instructor'),
  ('deporte', 'Probar wingfoil'),
  ('deporte', 'Hacer un bottom turn controlado'),
  ('deporte', 'Hacer una travesía costera en moto de agua con guía'),
  ('deporte', 'Obtener una certificación básica de buceo'),
  ('deporte', 'Probar apnea recreativa con instructor'),
  ('deporte', 'Probar hidrospeed con guía'),
  ('deporte', 'Hacer rafting nivel IV con guía'),
  ('deporte', 'Hacer un cutback básico'),
  ('deporte', 'Hacer un salto básico en wakeboard'),
  ('deporte', 'Hacer una inmersión nocturna con certificación adecuada'),
  ('deporte', 'Navegar 100 m en kitesurf de forma controlada'),
  ('deporte', 'Aprender jab, cross, hook y uppercut básicos'),
  ('deporte', 'Hacer una clase de BJJ'),
  ('deporte', 'Hacer una clase de Muay Thai'),
  ('deporte', 'Hacer una clase de boxeo'),
  ('deporte', 'Hacer una clase de defensa personal'),
  ('deporte', 'Hacer una clase de esgrima'),
  ('deporte', 'Hacer una clase de judo'),
  ('deporte', 'Hacer una clase de karate'),
  ('deporte', 'Hacer una clase de kickboxing'),
  ('deporte', 'Hacer una clase de lucha olímpica'),
  ('deporte', 'Hacer una clase de taekwondo'),
  ('deporte', 'Aprender 3 proyecciones básicas de judo'),
  ('deporte', 'Aprender un derribo de doble pierna'),
  ('deporte', 'Hacer rounds de saco de'),
  ('deporte', 'Romper una tabla en una demostración supervisada'),
  ('deporte', 'Hacer sparring técnico de Muay Thai con entrenador'),
  ('deporte', 'Hacer tu primer sparring técnico de boxeo con entrenador'),
  ('deporte', 'Participar en un randori controlado de judo'),
  ('deporte', 'Jugar un partido de baloncesto 5x5'),
  ('deporte', 'Jugar un partido de balonmano'),
  ('deporte', 'Jugar un partido de bádminton'),
  ('deporte', 'Jugar un partido de béisbol o softball'),
  ('deporte', 'Jugar un partido de fútbol sala'),
  ('deporte', 'Jugar un partido de pickleball'),
  ('deporte', 'Jugar un partido de pádel'),
  ('deporte', 'Jugar un partido de squash'),
  ('deporte', 'Jugar un partido de tenis'),
  ('deporte', 'Jugar un partido de voleibol'),
  ('deporte', 'Jugar vóley playa'),
  ('deporte', 'Jugar un partido completo de fútbol 11'),
  ('deporte', 'Jugar un partido de hockey hierba'),
  ('deporte', 'Jugar un partido de rugby touch'),
  ('deporte', 'Jugar un partido de waterpolo'),
  ('deporte', 'Jugar un torneo de fútbol 7'),
  ('deporte', 'Probar rugby 15 en entrenamiento'),
  ('deporte', 'Aprender a frenar en skateboard'),
  ('deporte', 'Probar longboard'),
  ('deporte', 'Probar patines en línea'),
  ('deporte', 'Probar surfskate'),
  ('deporte', 'Aprender a frenar en T'),
  ('deporte', 'Aprender un precision jump básico'),
  ('deporte', 'Hacer un vault básico en parkour'),
  ('deporte', 'Probar BMX en pump track'),
  ('deporte', 'Probar parkour con entrenador'),
  ('deporte', 'Aprender un salto básico con patines'),
  ('deporte', 'Completar una línea básica en skatepark'),
  ('deporte', 'Probar highline con sistema de seguridad y profesionales'),
  ('deporte', 'Aprender a hacer el nudo de ocho correctamente'),
  ('deporte', 'Probar escalada en rocódromo'),
  ('deporte', 'Aprender a asegurar con dispositivo asistido'),
  ('deporte', 'Escalar una vía de'),
  ('deporte', 'Hacer una salida de escalada en roca con guía'),
  ('deporte', 'Completar un circuito de campus board básico'),
  ('deporte', 'Hacer rappel de 30 m con supervisión'),
  ('deporte', 'Aprender maniobras básicas de reunión en curso'),
  ('deporte', 'Hacer una ruta de varios largos con guía'),
  ('deporte', 'Probar escalada tradicional con guía'),
  ('deporte', 'Probar psicobloc en zona autorizada y segura'),
  ('deporte', 'Completar un Hero WOD escalado'),
  ('deporte', 'Hacer double-unders seguidos'),
  ('deporte', 'Hacer toes-to-bar seguidos'),
  ('deporte', 'Hacer dominadas estrictas seguidas'),
  ('deporte', 'Probar yoke carry bajo supervisión'),
  ('deporte', 'Realizar un levantamiento de atlas stone bajo supervisión'),
  ('deporte', 'Completar repeticiones seguidas de peso muerto con el % de tu peso corporal'),
  ('deporte', 'Completar repeticiones seguidas de press banca con el % de tu peso corporal'),
  ('deporte', 'Completar repeticiones seguidas de press estricto con el % de tu peso corporal'),
  ('deporte', 'Completar repeticiones seguidas de sentadilla frontal con el % de tu peso corporal'),
  ('deporte', 'Completar repeticiones seguidas de sentadilla trasera con el % de tu peso corporal'),
  ('deporte', 'Completar una ruta con de desnivel positivo'),
  ('deporte', 'Hacer trekking en un desierto con guía'),
  ('deporte', 'Hacer trekking en una selva con guía'),
  ('deporte', 'Hacer una vía ferrata nivel medio con equipo adecuado'),
  ('deporte', 'Hacer una ruta glaciar con guía'),
  ('deporte', 'Hacer una vía ferrata difícil con guía'),
  ('deporte', 'Conducir un quad en una ruta guiada'),
  ('deporte', 'Probar descenso en trineo de verano'),
  ('deporte', 'Probar karting'),
  ('deporte', 'Hacer canyoning nivel iniciación con guía'),
  ('deporte', 'Probar conducción 4x4 en circuito'),
  ('deporte', 'Probar sandboarding en dunas'),
  ('deporte', 'Conducir un coche deportivo en circuito con instructor'),
  ('deporte', 'Hacer canyoning nivel intermedio con guía'),
  ('deporte', 'Hacer coasteering con guía'),
  ('deporte', 'Hacer una jornada de enduro en circuito o zona autorizada'),
  ('deporte', 'Probar conducción sobre hielo en circuito especializado'),
  ('deporte', 'Probar motocross en circuito con instructor'),
  ('deporte', 'Probar supermoto en circuito'),
  ('deporte', 'Hacer una experiencia de rally con instructor'),
  ('deporte', 'Hacer una tanda de track day como conductor con formación'),
  ('deporte', 'Probar puenting con operador certificado'),
  ('deporte', 'Probar una carrera de aventura con kayak, bici y trekking'),
  ('deporte', 'Aprender a hacer un viraje de voltereta'),
  ('deporte', 'Aprender una salida desde poyete'),
  ('deporte', 'Nadar 100 m con respiración bilateral'),
  ('deporte', 'Completar largos de piscina de'),
  ('deporte', 'Hacer 25 m subacuáticos solo en entrenamiento supervisado'),
  ('deporte', 'Probar esquí de fondo'),
  ('deporte', 'Probar patinaje sobre hielo'),
  ('deporte', 'Probar snowboard'),
  ('deporte', 'Probar trineo deportivo en pista'),
  ('deporte', 'Probar esquí nocturno'),
  ('deporte', 'Aprender a frenar en hockey stop sobre hielo'),
  ('deporte', 'Hacer carving limpio en pista azul'),
  ('deporte', 'Jugar un partido amateur de hockey sobre hielo'),
  ('deporte', 'Hacer carving limpio en pista roja'),
  ('deporte', 'Hacer un salto básico en snowpark'),
  ('deporte', 'Hacer una jornada de esquí de travesía con guía'),
  ('deporte', 'Probar esquí fuera de pista con guía y equipo'),
  ('deporte', 'Hacer 30 burpees de penalización y continuar corriendo'),
  ('deporte', 'Participar en una competición ninja amateur'),
  ('deporte', 'Aprender a usar brújula y mapa topográfico'),
  ('deporte', 'Probar marcha nórdica'),
  ('deporte', 'Aprender trote levantado'),
  ('deporte', 'Hacer una ruta en trineo de perros con operador responsable'),
  ('deporte', 'Probar polo en una clase de iniciación'),
  ('deporte', 'Aprender galope controlado con instructor'),
  ('deporte', 'Probar orientación a caballo'),
  ('deporte', 'Saltar un obstáculo básico con caballo e instructor'),
  ('deporte', 'Jugar una partida de billar'),
  ('deporte', 'Jugar una partida de dardos 501'),
  ('deporte', 'Probar disc golf'),
  ('deporte', 'Probar petanca en competición local'),
  ('deporte', 'Probar tiro con arco con instructor'),
  ('deporte', 'Completar un recorrido de 18 hoyos de disc golf'),
  ('deporte', 'Jugar 18 hoyos de golf'),
  ('deporte', 'Jugar una partida de bolos por encima de 150 puntos'),
  ('deporte', 'Jugar una partida de curling'),
  ('deporte', 'Acertar una diana a 30 m con arco en campo supervisado'),
  ('deporte', 'Hacer tres strikes seguidos'),
  ('deporte', 'Aprender a hacer malabares con 4 pelotas'),
  ('deporte', 'Probar remo en agua con instructor'),
  ('deporte', 'Aprender la técnica básica de remo en skiff'),
  ('deporte', 'Completar una sesión de'),
  ('deporte', 'Participar en una carrera de dragon boat'),
  ('deporte', 'Completar una carrera sin mirar el reloj'),
  ('deporte', 'Probar canicross'),
  ('deporte', 'Completar un trail de'),
  ('aventura', 'Hacer wakeboard'),
  ('aventura', 'Bucear bajo hielo con formacion especifica'),
  ('aventura', 'Hacer una inmersion nocturna'),
  ('aventura', 'Hacer una inmersion profunda de 30 m con certificacion'),
  ('aventura', 'Explorar una cueva submarina solo con certificacion tecnica'),
  ('aventura', 'Escalar una via de varios largos con guia'),
  ('aventura', 'Ascender el Mont Blanc con guia'),
  ('aventura', 'Ascender el Chimborazo con guia'),
  ('aventura', 'Hacer trekking en Patagonia sobre hielo con guia'),
  ('aventura', 'Hacer una jornada de freeride con guia'),
  ('aventura', 'Explorar una cueva de hielo natural con guia'),
  ('aventura', 'Ruta enduro guiada'),
  ('aventura', 'Safari nocturno guiado'),
  ('aventura', 'Ver osos grizzly con guia'),
  ('aventura', 'Ver ballenas jorobadas desde kayak guiado'),
  ('aventura', 'Caminar por selva amazonica con guia'),
  ('aventura', 'Expedicion al Danakil con operador autorizado'),
  ('aventura', 'Trekking por Kamchatka con guia'),
  ('aventura', 'Hacer kayak en la Antartida con guia'),
  ('aventura', 'Explorar una mina abandonada habilitada para visitas de aventura'),
  ('aventura', 'Descender con rapel a una sima con guia'),
  ('aventura', 'Hacer rapel de 50 m con instructor'),
  ('aventura', 'Subir por escaleras exteriores de un rascacielos habilitado'),
  ('aventura', 'Hacer parkour con instructor en entorno urbano'),
  ('aventura', 'Probar trampolin freestyle en centro especializado'),
  ('aventura', 'Hacer supervivencia 24 h con instructor'),
  ('aventura', 'Hacer supervivencia 48 h con instructor'),
  ('aventura', 'Dormir en hamaca en selva con guia'),
  ('gastronomia', 'Recorrer Addis Mercato con guia gastronomico'),
  ('gastronomia', 'Recorrer un mercado de Lagos con guia local'),
  ('cultura', 'Visitar las iglesias rupestres de Tigray con operador seguro'),
  ('cultura', 'Vivir Las Fallas'),
  ('cultura', 'Vivir San Fermin'),
  ('cultura', 'Vivir Festa de Sao Joao'),
  ('cultura', 'Vivir Meskel'),
  ('cultura', 'Vivir Inti Raymi'),
  ('cultura', 'Vivir Guelaguetza'),
  ('cultura', 'Vivir Junkanoo'),
  ('cultura', 'Vivir Crop Over'),
  ('cultura', 'Vivir Mardi Gras'),
  ('cultura', 'Vivir Quebec Winter Carnival'),
  ('cultura', 'Vivir Gion Matsuri'),
  ('cultura', 'Vivir Awa Odori'),
  ('cultura', 'Vivir Nebuta Matsuri'),
  ('cultura', 'Vivir Songkran'),
  ('cultura', 'Vivir Nyepi'),
  ('cultura', 'Vivir Sinulog'),
  ('cultura', 'Vivir Ati-Atihan'),
  ('cultura', 'Vivir Holi'),
  ('cultura', 'Vivir Diwali'),
  ('cultura', 'Vivir Pushkar Camel Fair'),
  ('cultura', 'Vivir Vivid Sydney'),
  ('cultura', 'Vivir Matariki'),
  ('cultura', 'Vivir Pasifika Festival'),
  ('cultura', 'Ver una actuacion de didgeridoo guiada por artistas aborigenes'),
  ('musica', 'Vivir Tomorrowland Belgium'),
  ('musica', 'Vivir Tomorrowland Winter'),
  ('musica', 'Vivir Ultra Music Festival Miami'),
  ('musica', 'Vivir EDC Las Vegas'),
  ('musica', 'Vivir EDC Mexico'),
  ('musica', 'Vivir Creamfields'),
  ('musica', 'Vivir Awakenings Festival'),
  ('musica', 'Vivir Mysteryland'),
  ('musica', 'Vivir Defqon.1'),
  ('musica', 'Vivir A State of Trance Festival'),
  ('musica', 'Vivir DGTL Amsterdam'),
  ('musica', 'Vivir Dekmantel'),
  ('musica', 'Vivir Amsterdam Dance Event'),
  ('musica', 'Vivir Loveland Festival'),
  ('musica', 'Vivir Time Warp'),
  ('musica', 'Vivir Parookaville'),
  ('musica', 'Vivir Nature One'),
  ('musica', 'Vivir Airbeat One'),
  ('musica', 'Vivir Melt Festival o sucesor de referencia si esta activo'),
  ('musica', 'Vivir Sonus Festival'),
  ('musica', 'Vivir Ultra Europe'),
  ('musica', 'Vivir Hideout Festival'),
  ('musica', 'Vivir Dimensions Festival'),
  ('musica', 'Vivir Exit Festival'),
  ('musica', 'Vivir Sziget Festival'),
  ('musica', 'Vivir Untold Festival'),
  ('musica', 'Vivir Neversea o festival costero sucesor oficial'),
  ('musica', 'Vivir Electric Castle'),
  ('musica', 'Vivir Balaton Sound si vuelve a celebrarse'),
  ('musica', 'Vivir Medusa Festival'),
  ('musica', 'Vivir Dreambeach'),
  ('musica', 'Vivir Aquasella'),
  ('musica', 'Vivir Monegros Desert Festival'),
  ('musica', 'Vivir Sonar Barcelona'),
  ('musica', 'Vivir Primavera Sound Barcelona'),
  ('musica', 'Vivir Mad Cool Festival'),
  ('musica', 'Vivir Bilbao BBK Live'),
  ('musica', 'Vivir Cruilla'),
  ('musica', 'Vivir Vida Festival'),
  ('musica', 'Vivir Rototom Sunsplash'),
  ('musica', 'Vivir FIB Benicassim'),
  ('musica', 'Vivir Resurrection Fest'),
  ('musica', 'Vivir Leyendas del Rock'),
  ('musica', 'Vivir Rock Fest Barcelona si se celebra'),
  ('musica', 'Vivir WARM UP Estrella de Levante'),
  ('musica', 'Vivir Riverland Fest'),
  ('musica', 'Vivir O Son do Camino'),
  ('musica', 'Vivir Nos Alive'),
  ('musica', 'Vivir Super Bock Super Rock'),
  ('musica', 'Vivir Boom Festival'),
  ('musica', 'Vivir Neopop Festival'),
  ('musica', 'Vivir Rock in Rio Lisboa'),
  ('musica', 'Vivir IleSoniq'),
  ('musica', 'Vivir Osheaga'),
  ('musica', 'Vivir Shambhala Music Festival'),
  ('musica', 'Vivir Veld Music Festival'),
  ('musica', 'Vivir Coachella'),
  ('musica', 'Vivir Stagecoach'),
  ('musica', 'Vivir Lollapalooza Chicago'),
  ('musica', 'Vivir Austin City Limits'),
  ('musica', 'Vivir Bonnaroo'),
  ('musica', 'Vivir Electric Forest'),
  ('musica', 'Vivir Burning Man'),
  ('musica', 'Vivir Outside Lands'),
  ('musica', 'Vivir Governors Ball'),
  ('musica', 'Vivir Rolling Loud Miami'),
  ('musica', 'Vivir Movement Detroit'),
  ('musica', 'Vivir ARC Music Festival'),
  ('musica', 'Vivir Hard Summer'),
  ('musica', 'Vivir Beyond Wonderland'),
  ('musica', 'Vivir Nocturnal Wonderland'),
  ('musica', 'Vivir Electric Zoo o sucesor neoyorquino vigente'),
  ('musica', 'Vivir Lightning in a Bottle'),
  ('musica', 'Vivir CRSSD Festival'),
  ('musica', 'Vivir New Orleans Jazz & Heritage Festival'),
  ('musica', 'Vivir Essence Festival'),
  ('musica', 'Vivir Pitchfork Music Festival si se celebra'),
  ('musica', 'Vivir Boston Calling'),
  ('musica', 'Vivir Riot Fest'),
  ('musica', 'Vivir When We Were Young'),
  ('musica', 'Vivir Sick New World si se celebra'),
  ('musica', 'Vivir Welcome to Rockville'),
  ('musica', 'Vivir Aftershock Festival'),
  ('musica', 'Vivir Louder Than Life'),
  ('musica', 'Vivir EDC Orlando'),
  ('musica', 'Vivir Ultra Worldwide en una sede internacional'),
  ('musica', 'Vivir Lollapalooza Argentina'),
  ('musica', 'Vivir Lollapalooza Chile'),
  ('musica', 'Vivir Lollapalooza Brasil'),
  ('musica', 'Vivir Rock in Rio'),
  ('musica', 'Vivir The Town'),
  ('musica', 'Vivir Tomorrowland Brasil si la edicion esta activa'),
  ('musica', 'Vivir Creamfields Argentina'),
  ('musica', 'Vivir Estereo Picnic'),
  ('musica', 'Vivir Baum Festival'),
  ('musica', 'Vivir Corona Capital'),
  ('musica', 'Vivir Vive Latino'),
  ('musica', 'Vivir Tecate Pal Norte'),
  ('musica', 'Vivir Bahidora'),
  ('musica', 'Vivir Ceremonia'),
  ('musica', 'Vivir Festival de Vina del Mar'),
  ('musica', 'Vivir Cosquin Rock'),
  ('musica', 'Vivir Festival Cordillera'),
  ('musica', 'Vivir Glastonbury Festival'),
  ('musica', 'Vivir Reading Festival'),
  ('musica', 'Vivir Leeds Festival'),
  ('musica', 'Vivir Download Festival'),
  ('musica', 'Vivir Isle of Wight Festival'),
  ('musica', 'Vivir TRNSMT'),
  ('musica', 'Vivir Wireless Festival'),
  ('musica', 'Vivir All Points East'),
  ('musica', 'Vivir BST Hyde Park'),
  ('musica', 'Vivir Parklife'),
  ('musica', 'Vivir Boardmasters'),
  ('musica', 'Vivir Boomtown Fair'),
  ('musica', 'Vivir Lost Village'),
  ('musica', 'Vivir Field Day'),
  ('musica', 'Vivir Lovebox o sucesor activo'),
  ('musica', 'Vivir Rock Werchter'),
  ('musica', 'Vivir Pukkelpop'),
  ('musica', 'Vivir Graspop Metal Meeting'),
  ('musica', 'Vivir Dour Festival'),
  ('musica', 'Vivir Les Ardentes'),
  ('musica', 'Vivir Hellfest'),
  ('musica', 'Vivir Hellfest Open Air'),
  ('musica', 'Vivir Main Square Festival'),
  ('musica', 'Vivir Les Vieilles Charrues'),
  ('musica', 'Vivir Garorock'),
  ('musica', 'Vivir Solidays'),
  ('musica', 'Vivir We Love Green'),
  ('musica', 'Vivir Cabaret Vert'),
  ('musica', 'Vivir Eurockeennes'),
  ('musica', 'Vivir Rock en Seine'),
  ('musica', 'Vivir Festival Beauregard'),
  ('musica', 'Vivir Lowlands'),
  ('musica', 'Vivir Pinkpop'),
  ('musica', 'Vivir North Sea Jazz Festival'),
  ('musica', 'Vivir Roadburn Festival'),
  ('musica', 'Vivir Wacken Open Air'),
  ('musica', 'Vivir Rock am Ring'),
  ('musica', 'Vivir Rock im Park'),
  ('musica', 'Vivir Hurricane Festival'),
  ('musica', 'Vivir Southside Festival'),
  ('musica', 'Vivir Fusion Festival'),
  ('musica', 'Vivir Reeperbahn Festival'),
  ('musica', 'Vivir Lollapalooza Berlin'),
  ('musica', 'Vivir Open''er Festival'),
  ('musica', 'Vivir Pol''and''Rock Festival'),
  ('musica', 'Vivir OFF Festival'),
  ('musica', 'Vivir Colours of Ostrava'),
  ('musica', 'Vivir Pohoda Festival'),
  ('musica', 'Vivir Nova Rock'),
  ('musica', 'Vivir Frequency Festival'),
  ('musica', 'Vivir INmusic Festival'),
  ('musica', 'Vivir Sea Star Festival'),
  ('musica', 'Vivir Sunny Hill Festival'),
  ('musica', 'Vivir Roskilde Festival'),
  ('musica', 'Vivir Copenhell'),
  ('musica', 'Vivir Distortion'),
  ('musica', 'Vivir Way Out West'),
  ('musica', 'Vivir Sweden Rock Festival'),
  ('musica', 'Vivir Flow Festival'),
  ('musica', 'Vivir Provinssi'),
  ('musica', 'Vivir Ruisrock'),
  ('musica', 'Vivir Oya Festival'),
  ('musica', 'Vivir Tons of Rock'),
  ('musica', 'Vivir Bergenfest'),
  ('musica', 'Vivir Iceland Airwaves'),
  ('musica', 'Vivir Secret Solstice si esta activo'),
  ('musica', 'Vivir Montreux Jazz Festival'),
  ('musica', 'Vivir Paléo Festival'),
  ('musica', 'Vivir OpenAir St. Gallen'),
  ('musica', 'Vivir Zurich Openair'),
  ('musica', 'Vivir Lucca Summer Festival'),
  ('musica', 'Vivir I-Days Milano'),
  ('musica', 'Vivir Rock in Roma'),
  ('musica', 'Vivir Firenze Rocks'),
  ('musica', 'Vivir Kappa FuturFestival'),
  ('musica', 'Vivir Nameless Festival'),
  ('musica', 'Vivir Home Festival o sucesor activo'),
  ('musica', 'Vivir Guca Trumpet Festival'),
  ('musica', 'Vivir Athens Epidaurus contemporary music events'),
  ('musica', 'Vivir Ejekt Festival'),
  ('musica', 'Vivir Release Athens'),
  ('musica', 'Vivir Sunwaves Festival si se celebra'),
  ('musica', 'Vivir Untold Dubai si existe una edicion vigente'),
  ('musica', 'Vivir MDLBEAST Soundstorm'),
  ('musica', 'Vivir Sole DXB music program'),
  ('musica', 'Vivir Sunburn Festival'),
  ('musica', 'Vivir NH7 Weekender'),
  ('musica', 'Vivir Magnetic Fields Festival'),
  ('musica', 'Vivir Ziro Festival of Music'),
  ('musica', 'Vivir Fuji Rock Festival'),
  ('musica', 'Vivir Summer Sonic'),
  ('musica', 'Vivir Rock in Japan'),
  ('musica', 'Vivir Ultra Japan'),
  ('musica', 'Vivir EDC Korea si se celebra'),
  ('musica', 'Vivir Pentaport Rock Festival'),
  ('musica', 'Vivir Clockenflap'),
  ('musica', 'Vivir Creamfields Hong Kong si se celebra'),
  ('musica', 'Vivir ZoukOut'),
  ('musica', 'Vivir We The Fest'),
  ('musica', 'Vivir Djakarta Warehouse Project'),
  ('musica', 'Vivir Wonderfruit'),
  ('musica', 'Vivir 808 Festival'),
  ('musica', 'Vivir Rolling Loud Thailand si se celebra'),
  ('musica', 'Vivir Good Vibes Festival si se celebra'),
  ('musica', 'Vivir Rainforest World Music Festival'),
  ('musica', 'Vivir Java Jazz Festival'),
  ('musica', 'Vivir Fuji Rock'),
  ('musica', 'Vivir Laneway Festival'),
  ('musica', 'Vivir Splendour in the Grass si regresa'),
  ('musica', 'Vivir Beyond the Valley'),
  ('musica', 'Vivir Pitch Music & Arts'),
  ('musica', 'Vivir Wildlands'),
  ('musica', 'Vivir Field Day Sydney'),
  ('musica', 'Vivir Ultra Australia'),
  ('musica', 'Vivir Rhythm and Vines'),
  ('musica', 'Vivir Electric Avenue'),
  ('musica', 'Vivir Homegrown'),
  ('musica', 'Vivir Cape Town International Jazz Festival'),
  ('musica', 'Vivir AfrikaBurn'),
  ('musica', 'Vivir Rocking the Daisies'),
  ('musica', 'Vivir Ultra South Africa'),
  ('musica', 'Vivir Mawazine'),
  ('musica', 'Vivir Essaouira Gnaoua and World Music Festival'),
  ('musica', 'Vivir Festival au Desert o equivalente seguro'),
  ('musica', 'Vivir Sauti za Busara'),
  ('musica', 'Vivir Lake of Stars'),
  ('musica', 'Vivir Felabration'),
  ('musica', 'Vivir Afro Nation Portugal'),
  ('musica', 'Vivir Afro Nation Ghana si se celebra'),
  ('musica', 'Ver un concierto en Red Rocks Amphitheatre'),
  ('musica', 'Ver un concierto en Madison Square Garden'),
  ('musica', 'Ver un concierto en Radio City Music Hall'),
  ('musica', 'Ver un concierto en Carnegie Hall'),
  ('musica', 'Ver un concierto en Hollywood Bowl'),
  ('musica', 'Ver un concierto en The Greek Theatre'),
  ('musica', 'Ver un concierto en The Gorge Amphitheatre'),
  ('musica', 'Ver un concierto en Ryman Auditorium'),
  ('musica', 'Ver un concierto en Grand Ole Opry'),
  ('musica', 'Ver un concierto en The Fillmore'),
  ('musica', 'Ver un concierto en Preservation Hall'),
  ('musica', 'Ver jazz en Village Vanguard'),
  ('musica', 'Ver jazz en Blue Note New York'),
  ('musica', 'Ver una banda en The Troubadour'),
  ('musica', 'Ver una banda en Whisky a Go Go'),
  ('musica', 'Ver musica en 9:30 Club'),
  ('musica', 'Ver un concierto en Massey Hall'),
  ('musica', 'Ver jazz en Upstairs Jazz Bar'),
  ('musica', 'Ver un concierto en Royal Albert Hall'),
  ('musica', 'Ver un concierto en Wembley Stadium'),
  ('musica', 'Ver un concierto en O2 Arena'),
  ('musica', 'Ver un concierto en Brixton Academy'),
  ('musica', 'Ver un concierto en Roundhouse'),
  ('musica', 'Ver un concierto en Alexandra Palace'),
  ('musica', 'Ver un concierto en Union Chapel'),
  ('musica', 'Ver una banda en King Tut''s Wah Wah Hut'),
  ('musica', 'Ver una banda en Barrowland Ballroom'),
  ('musica', 'Ver un concierto en Manchester Arena'),
  ('musica', 'Ver un concierto en Paradiso'),
  ('musica', 'Ver un concierto en Melkweg'),
  ('musica', 'Salir a Berghain si se logra entrar'),
  ('musica', 'Vivir una noche en Tresor'),
  ('musica', 'Vivir una noche en RSO Berlin'),
  ('musica', 'Ver un concierto en Waldbühne'),
  ('musica', 'Ver musica clasica en Berliner Philharmonie'),
  ('musica', 'Ver un concierto en Elbphilharmonie'),
  ('musica', 'Ver musica clasica en Musikverein'),
  ('musica', 'Ver opera en Wiener Staatsoper'),
  ('musica', 'Ver un concierto en Olympia'),
  ('musica', 'Ver un concierto en Accor Arena'),
  ('musica', 'Ver musica en Philharmonie de Paris'),
  ('musica', 'Ver opera en Palais Garnier'),
  ('musica', 'Ver un concierto en Zenith Paris'),
  ('musica', 'Ver un concierto en Ziggo Dome'),
  ('musica', 'Ver musica en Concertgebouw'),
  ('musica', 'Ver un concierto en Sportpaleis'),
  ('musica', 'Ver musica clasica en BOZAR'),
  ('musica', 'Ver un concierto en WiZink/Movistar Arena Madrid'),
  ('musica', 'Ver un concierto en Estadi Olimpic'),
  ('musica', 'Ver un concierto en Palau Sant Jordi'),
  ('musica', 'Ver musica en Palau de la Musica Catalana'),
  ('musica', 'Ver un concierto en Razzmatazz'),
  ('musica', 'Ver un concierto en Apolo'),
  ('musica', 'Vivir una noche en Fabrik'),
  ('musica', 'Vivir una noche en INPUT'),
  ('musica', 'Vivir una noche en Amnesia Ibiza'),
  ('musica', 'Vivir una noche en Pacha Ibiza'),
  ('musica', 'Vivir una noche en Hï Ibiza'),
  ('musica', 'Vivir una noche en Ushuaia Ibiza'),
  ('musica', 'Vivir una noche en DC-10'),
  ('musica', 'Ver un concierto en Coliseu dos Recreios'),
  ('musica', 'Ver fado en Clube de Fado'),
  ('musica', 'Ver una opera en Teatro alla Scala'),
  ('musica', 'Ver un concierto en Arena di Verona'),
  ('musica', 'Ver un concierto en Auditorium Parco della Musica'),
  ('musica', 'Ver una opera en La Fenice'),
  ('musica', 'Vivir una noche en Cocorico'),
  ('musica', 'Ver un concierto en OAKA'),
  ('musica', 'Ver musica en Odeon of Herodes Atticus'),
  ('musica', 'Ver un concierto en Puskas Arena'),
  ('musica', 'Ver un concierto en O2 Arena Prague'),
  ('musica', 'Ver un concierto en Tauron Arena'),
  ('musica', 'Ver un concierto en Atlas Arena'),
  ('musica', 'Ver un concierto en Avicii Arena'),
  ('musica', 'Ver musica clasica en Stockholm Concert Hall'),
  ('musica', 'Ver un concierto en Royal Arena'),
  ('musica', 'Ver un concierto en Oslo Spektrum'),
  ('musica', 'Ver musica en Harpa'),
  ('musica', 'Ver un concierto en Hallenstadion'),
  ('musica', 'Ver musica en KKL Luzern'),
  ('musica', 'Ver un concierto en Accor? no repetir'),
  ('musica', 'Ver musica en Dubai Opera'),
  ('musica', 'Ver un concierto en Etihad Arena'),
  ('musica', 'Ver musica en Royal Opera House Muscat'),
  ('musica', 'Ver un concierto en Coca-Cola Arena'),
  ('musica', 'Ver musica clasica en Suntory Hall'),
  ('musica', 'Ver un concierto en Nippon Budokan'),
  ('musica', 'Ver un concierto en Tokyo Dome'),
  ('musica', 'Ver jazz en Blue Note Tokyo'),
  ('musica', 'Ver un concierto en Osaka-jō Hall'),
  ('musica', 'Ver un concierto en Gocheok Sky Dome'),
  ('musica', 'Ver un concierto en KSPO Dome'),
  ('musica', 'Ver una actuacion en Seoul Arts Center'),
  ('musica', 'Ver un concierto en AsiaWorld-Arena'),
  ('musica', 'Ver musica en Hong Kong Cultural Centre'),
  ('musica', 'Ver un concierto en Singapore Indoor Stadium'),
  ('musica', 'Ver musica en Esplanade Concert Hall'),
  ('musica', 'Vivir una noche en Zouk Singapore'),
  ('musica', 'Ver un concierto en Impact Arena'),
  ('musica', 'Vivir una noche en Zouk Kuala Lumpur'),
  ('musica', 'Ver un concierto en Istora Senayan'),
  ('musica', 'Ver un concierto en Mall of Asia Arena'),
  ('musica', 'Ver musica en NCPA'),
  ('musica', 'Ver un concierto en Jawaharlal Nehru Stadium'),
  ('musica', 'Ver un concierto en Sydney Opera House'),
  ('musica', 'Ver un concierto en Hordern Pavilion'),
  ('musica', 'Ver un concierto en Rod Laver Arena'),
  ('musica', 'Ver musica en Sidney Myer Music Bowl'),
  ('musica', 'Ver un concierto en Spark Arena'),
  ('musica', 'Ver un concierto en The Powerstation'),
  ('musica', 'Ver un concierto en Foro Sol/Estadio GNP'),
  ('musica', 'Ver un concierto en Auditorio Nacional'),
  ('musica', 'Ver una banda en Foro Indie Rocks'),
  ('musica', 'Ver un concierto en Movistar Arena'),
  ('musica', 'Ver un concierto en Estadio River Plate'),
  ('musica', 'Ver tango en vivo con orquesta'),
  ('musica', 'Ver un concierto en Allianz Parque'),
  ('musica', 'Ver samba en vivo en Lapa'),
  ('musica', 'Ver un concierto en Movistar Arena Santiago'),
  ('musica', 'Ver musica en Teatro Colon'),
  ('musica', 'Ver musica en Teatro Municipal'),
  ('musica', 'Ver un concierto en Movistar Arena Bogota'),
  ('musica', 'Ver salsa en vivo'),
  ('musica', 'Ver un concierto en GrandWest Arena'),
  ('musica', 'Ver jazz en The Orbit o club de referencia vigente'),
  ('musica', 'Recorrer Abbey Road y visitar su entorno musical'),
  ('musica', 'Hacer una ruta de The Beatles'),
  ('musica', 'Visitar The Cavern Club'),
  ('musica', 'Visitar British Music Experience'),
  ('musica', 'Hacer una ruta de David Bowie'),
  ('musica', 'Hacer una ruta del punk britanico'),
  ('musica', 'Recorrer Manchester siguiendo Joy Division y Factory Records'),
  ('musica', 'Visitar Salford Lads Club'),
  ('musica', 'Recorrer Glasgow descubriendo su escena indie'),
  ('musica', 'Hacer una ruta de U2'),
  ('musica', 'Visitar instrumentos historicos en museo musical'),
  ('musica', 'Visitar Beethoven-Haus'),
  ('musica', 'Visitar Bach Museum'),
  ('musica', 'Visitar Mozart Geburtshaus'),
  ('musica', 'Visitar Haus der Musik'),
  ('musica', 'Seguir la Viena de Mozart, Beethoven y Schubert'),
  ('musica', 'Visitar Chopin Museum'),
  ('musica', 'Escuchar Chopin en un recital'),
  ('musica', 'Vivir una noche de reggae en Kingston'),
  ('musica', 'Visitar Graceland'),
  ('musica', 'Visitar Sun Studio'),
  ('musica', 'Visitar Stax Museum'),
  ('musica', 'Visitar National Museum of African American Music'),
  ('musica', 'Visitar Country Music Hall of Fame'),
  ('musica', 'Recorrer Broadway honky-tonks'),
  ('musica', 'Visitar Rock & Roll Hall of Fame'),
  ('musica', 'Visitar Motown Museum'),
  ('musica', 'Vivir una noche de techno en Detroit'),
  ('musica', 'Visitar house music landmarks'),
  ('musica', 'Vivir blues en Chicago'),
  ('musica', 'Vivir jazz en New Orleans'),
  ('musica', 'Seguir la historia del hip-hop en Bronx'),
  ('musica', 'Visitar Apollo Theater'),
  ('musica', 'Vivir una jam session de jazz'),
  ('musica', 'Visitar Museum of Pop Culture'),
  ('musica', 'Seguir la historia del grunge'),
  ('musica', 'Visitar Jimi Hendrix memorial'),
  ('musica', 'Visitar Paisley Park'),
  ('musica', 'Visitar Buddy Holly Center'),
  ('musica', 'Visitar Johnny Cash Museum'),
  ('musica', 'Visitar Studio Bell National Music Centre'),
  ('musica', 'Vivir folk y chanson en Montreal'),
  ('musica', 'Visitar Museo del Rock argentino o ruta equivalente'),
  ('musica', 'Vivir tango en una milonga'),
  ('musica', 'Vivir cumbia villera o escena tropical en contexto seguro'),
  ('musica', 'Vivir samba de roda'),
  ('musica', 'Vivir forro en vivo'),
  ('musica', 'Vivir bossa nova en Rio'),
  ('musica', 'Vivir sertanejo en una gran fiesta'),
  ('musica', 'Vivir cumbia colombiana'),
  ('musica', 'Vivir salsa en Cali'),
  ('musica', 'Vivir vallenato'),
  ('musica', 'Vivir son cubano en vivo'),
  ('musica', 'Visitar casas de musica tradicional'),
  ('musica', 'Vivir mariachi en Plaza Garibaldi'),
  ('musica', 'Vivir banda sinaloense en directo'),
  ('musica', 'Vivir norteño en el norte de Mexico'),
  ('musica', 'Vivir musica andina en vivo'),
  ('musica', 'Vivir cueca chilena'),
  ('musica', 'Vivir afrobeat en Lagos'),
  ('musica', 'Visitar The New Afrika Shrine'),
  ('musica', 'Vivir highlife en Ghana'),
  ('musica', 'Vivir amapiano en Johannesburgo'),
  ('musica', 'Vivir gqom en Durban'),
  ('musica', 'Vivir jazz sudafricano'),
  ('musica', 'Vivir gnawa en Essaouira'),
  ('musica', 'Vivir rai en Argelia o diaspora'),
  ('musica', 'Vivir taarab en Zanzibar'),
  ('musica', 'Vivir ethiopian jazz'),
  ('musica', 'Vivir mbalax en Dakar'),
  ('musica', 'Vivir soukous en Kinshasa con seguridad'),
  ('musica', 'Vivir qawwali en un santuario o concierto respetuoso'),
  ('musica', 'Vivir musica carnatic'),
  ('musica', 'Vivir musica hindustani'),
  ('musica', 'Vivir Bollywood music show'),
  ('musica', 'Vivir gamelan'),
  ('musica', 'Vivir dangdut'),
  ('musica', 'Vivir K-pop en Seul'),
  ('musica', 'Asistir a un music show de K-pop con publico'),
  ('musica', 'Visitar HYBE Insight o experiencia oficial equivalente si esta disponible'),
  ('musica', 'Vivir J-pop en Tokio'),
  ('musica', 'Ir a un concierto de idol culture con respeto'),
  ('musica', 'Vivir city pop en un listening bar'),
  ('musica', 'Visitar una tienda de vinilos de Shibuya'),
  ('musica', 'Vivir jazz kissa'),
  ('musica', 'Cantar karaoke en Tokio con amigos'),
  ('musica', 'Vivir cantopop en Hong Kong'),
  ('musica', 'Vivir mandopop en Taipei'),
  ('musica', 'Vivir musica tradicional china en directo'),
  ('musica', 'Vivir opera cantonesa'),
  ('musica', 'Vivir pinpeat camboyano'),
  ('musica', 'Vivir ca tru o musica tradicional vietnamita'),
  ('musica', 'Vivir luk thung o mor lam'),
  ('musica', 'Vivir musica maori en un evento cultural'),
  ('musica', 'Vivir musica aborigen australiana en festival cultural'),
  ('musica', 'Crear una coleccion de 50 vinilos elegidos por significado personal'),
  ('musica', 'Aprender a mezclar dos canciones como DJ sin sync'),
  ('musica', 'Grabar un DJ set de 30 minutos'),
  ('musica', 'Grabar un DJ set de 60 minutos'),
  ('musica', 'Tocar un DJ set frente a amigos'),
  ('musica', 'Tocar un DJ set en un bar o evento pequeno'),
  ('musica', 'Tocar un DJ set en un club'),
  ('musica', 'Tocar en un festival como DJ'),
  ('musica', 'Producir una cancion electronica completa'),
  ('musica', 'Publicar una cancion propia en plataformas'),
  ('musica', 'Hacer un remix terminado'),
  ('musica', 'Aprender teoria musical basica aplicada a produccion'),
  ('musica', 'Aprender a tocar 10 canciones en un instrumento'),
  ('musica', 'Tocar una cancion completa frente a publico'),
  ('musica', 'Componer una letra propia'),
  ('musica', 'Escribir y grabar una cancion con amigos'),
  ('musica', 'Cantar en un karaoke en un idioma que no dominas'),
  ('musica', 'Ver a tu artista favorito en directo'),
  ('musica', 'Ver a una banda legendaria antes de que deje de girar'),
  ('musica', 'Viajar a otro pais solo por un concierto'),
  ('musica', 'Hacer un road trip para asistir a varios conciertos'),
  ('musica', 'Asistir a 10 conciertos en un año'),
  ('musica', 'Asistir a 5 festivales distintos en un año'),
  ('musica', 'Ver un concierto desde primera fila'),
  ('musica', 'Conseguir acceso backstage de forma legitima'),
  ('musica', 'Ver un concierto en un estadio con mas de 50.000 personas'),
  ('musica', 'Ver un concierto intimista de menos de 200 personas'),
  ('musica', 'Descubrir una banda desconocida y verla antes de hacerse grande'),
  ('musica', 'Comprar un disco directamente a un artista independiente'),
  ('musica', 'Asistir a una firma o meet & greet oficial'),
  ('musica', 'Ir a un listening party de un album'),
  ('musica', 'Escuchar un album completo en vinilo sin usar el movil'),
  ('musica', 'Hacer una ruta por tiendas de discos en otra ciudad'),
  ('musica', 'Asistir a un concierto sin grabar ningun video'),
  ('musica', 'Aprender a reconocer 20 subgeneros de musica electronica'),
  ('musica', 'Crear una playlist de 100 canciones que cuente tu vida'),
  ('musica', 'Organizar una fiesta con un concepto musical propio'),
  ('musica', 'Crear una sesion que mezcle 3 generos diferentes'),
  ('musica', 'Hacer un set sunrise'),
  ('musica', 'Hacer un set sunset'),
  ('musica', 'Ver un sunrise set de un DJ'),
  ('musica', 'Ver una orquesta sinfonica interpretando una banda sonora'),
  ('musica', 'Ver una orquesta interpretar Beethoven en vivo'),
  ('musica', 'Ver una orquesta interpretar Mahler en vivo'),
  ('musica', 'Ver un requiem de Mozart en vivo'),
  ('musica', 'Ver Carmina Burana en vivo'),
  ('musica', 'Ver una opera completa por primera vez'),
  ('musica', 'Ver un ballet con orquesta en directo'),
  ('musica', 'Ver un coro gospel en contexto autentico y respetuoso'),
  ('musica', 'Asistir a un concierto de musica sacra en una catedral'),
  ('musica', 'Escuchar un organo historico en una iglesia'),
  ('espectaculos', 'Ir al festival de Glastonbury'),
  ('espectaculos', 'Ir al Sónar'),
  ('espectaculos', 'Ir al Mad Cool'),
  ('espectaculos', 'Ir al Bilbao BBK Live');


-- ── 1. El borrado, saltando lo que esté en alguna lista ────
delete from gooals_v2 g
using a_borrar b
where g.categoria = b.categoria
  and g.titulo = b.titulo
  and not exists (select 1 from user_gooals u where u.gooal_id = g.id);


-- ── 2. Qué se ha salvado por estar en la lista de alguien ──
-- Lo normal es que salga vacío.
select g.categoria, g.titulo, count(u.id) as personas
from gooals_v2 g
join a_borrar b on b.categoria = g.categoria and b.titulo = g.titulo
left join user_gooals u on u.gooal_id = g.id
group by g.categoria, g.titulo order by 3 desc;


-- ── 3. Comprobación ────────────────────────────────────────
-- Debe quedar en 3.992 filas. Las 734 que faltan las sube insertar.mjs
-- después, y ahí llegará a 4.726.
select categoria, count(*) as gooals
from gooals_v2 group by categoria order by 2 desc;
